# Vision-Language Models for Spatial Understanding  
## Notebook 2 — Automatic Extraction and Proxy Ground-Truth Construction

### Mehregan Nazarmohsenifakori

This notebook implements the **automatic extraction pipeline** used to build proxy ground-truth labels for the generated images.

## Project Role of This Notebook
The overall goal of the project is to study whether **Vision-Language Models (VLMs)** can serve as reliable judges of compositional failures in text-to-image generation. To evaluate the VLM judges, we first need an **automatic reference signal** derived directly from the generated images.

This notebook provides that reference through a multi-stage extraction pipeline:
1. **Step 2**: object detection and coarse spatial reasoning using bounding boxes,
2. **Step 3**: segmentation-based refinement using SAM3 and pixel-level reasoning,
3. **Numeracy refinement**: counting object instances using detection and segmentation.

These outputs are used later as **proxy ground truth** for comparison with VLM-as-a-Judge scores.

## Why Proxy Ground Truth?
The benchmark prompts define the intended scene composition, but the generated images do not come with human annotations. Therefore, instead of true human ground truth, this notebook constructs an **automatic proxy ground-truth pipeline**.

This proxy is not assumed to be perfect. Instead, it serves as:
- a reproducible baseline,
- an automatic extraction-based reference,
- and a point of comparison for the VLM judges.

## Main Outputs of This Notebook
This notebook produces three main outputs:
- `auto_labels_step2_bbox.csv`
- `auto_labels_step3_sam3.csv`
- `auto_labels_numeracy_sam3_refined.csv`

These files are stored in Google Drive and later merged with VLM judge results in the final analysis notebook.

## 1. Google Drive Setup and Input Files

This section mounts Google Drive and defines the project paths used throughout the notebook.

The main input to this notebook is the **master image index** produced in Notebook 1. That index contains:
- prompt IDs,
- original prompt text,
- dataset split,
- generator model,
- random seed,
- and image file path.

Using a shared master index ensures that extraction, segmentation, and later evaluation are all aligned on the same set of generated images.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import os
DRIVE_ROOT = "/content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding"
DIR_TABLES = os.path.join(DRIVE_ROOT, "tables")
os.makedirs(DIR_TABLES, exist_ok=True)

MASTER_CSV = os.path.join(DIR_TABLES, "master_generated_index.csv")
print("MASTER_CSV:", MASTER_CSV)
assert os.path.exists(MASTER_CSV), "master_generated_index.csv not found in Drive tables/"

## 2. Environment Setup

This notebook uses multiple vision models and therefore requires careful package setup. In particular, it relies on:
- `transformers` for OWL-ViT object detection,
- `torch` for GPU inference,
- `pandas` and `numpy` for metadata and numerical operations,
- and later the official `sam3` repository for segmentation refinement.

Because some package combinations can lead to binary incompatibilities in Colab, the environment is configured carefully before running the extraction pipeline.

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

In [ ]:
from huggingface_hub import login
login()

In [ ]:
!pip uninstall -y transformers
!pip install -U transformers accelerate

In [ ]:
!pip -q install -U "transformers==4.48.0" accelerate huggingface_hub torchvision opencv-python

In [ ]:
import re, json, math, gc
import numpy as np
import pandas as pd
from PIL import Image
import torch

def clear_vram():
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
        torch.cuda.ipc_collect()

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
DTYPE  = torch.bfloat16 if (DEVICE=="cuda" and torch.cuda.get_device_capability(0)[0] >= 8) else torch.float16
print("DEVICE:", DEVICE, "DTYPE:", DTYPE)

## 3. Load and Normalize the Master Image Index

In this section, the master index generated in Notebook 1 is loaded into memory.  
The split labels are normalized so that all downstream processing uses a consistent naming convention across:
- `spatial`
- `3d_spatial`
- `numeracy`
- `complex`

This table becomes the central reference for all extraction and proxy-label steps in the notebook.

In [ ]:
master_df = pd.read_csv(MASTER_CSV)

def norm_split(s):
    s = str(s).strip().lower()
    if s in ["3dspatial", "3d_spatial", "3d-spatial"]:
        return "3d_spatial"
    if s in ["numeric", "numeracy"]:
        return "numeracy"
    return s

master_df["split"] = master_df["split"].apply(norm_split)
print(master_df["split"].value_counts())
master_df.head()

## 4. Prompt Parsing and Relation Extraction

To evaluate generated images automatically, the prompt text must first be converted into a structured representation.

This section defines:
- the target **2D spatial relations** used in the benchmark,
- the target **3D spatial relations** used in the benchmark,
- and helper functions for extracting objects, relations, and counts from the prompt text.

These parsed elements are later used to:
- guide object detection,
- evaluate spatial relations,
- and construct numeracy targets.

In [ ]:
REL_2D = [
    ("side_of",   r"\bon the side of\b"),
    ("next_to",   r"\bnext to\b"),
    ("near",      r"\bnear\b"),
    ("left_of",   r"\bon the left of\b"),
    ("right_of",  r"\bon the right of\b"),
    ("bottom_of", r"\bon the bottom of\b"),
    ("top_of",    r"\bon the top of\b"),
]
REL_3D = [
    ("in_front_of", r"\bin front of\b"),
    ("behind",      r"\bbehind\b"),
    ("hidden_by",   r"\bhidden by\b"),
]

def find_relation(text: str):
    t = text.lower()
    for name, pat in REL_2D:
        m = re.search(pat, t)
        if m: return name, m.span(), "2d"
    for name, pat in REL_3D:
        m = re.search(pat, t)
        if m: return name, m.span(), "3d"
    return None, None, None

COLOR_WORDS = r"(red|blue|green|yellow|black|white|orange|purple|pink|brown|gray|grey)"
ARTICLES = r"(a|an|the)"

def clean_np(s: str):
    s = s.strip(" ,.")
    s = re.sub(rf"^{ARTICLES}\s+", "", s)
    s = re.sub(rf"\b{COLOR_WORDS}\b", "", s)
    s = re.sub(r"\s+", " ", s).strip(" ,.")
    return s

def parse_two_object_relation(text: str):
    rel, span, kind = find_relation(text)
    if rel is None:
        return {"parseable": 0}
    t = text.lower().strip()
    left = t[:span[0]].strip()
    right = t[span[1]:].strip()
    obj1 = clean_np(left)
    obj2 = clean_np(right)
    if len(obj1) < 2 or len(obj2) < 2:
        return {"parseable": 0}
    return {"parseable": 1, "obj1": obj1, "obj2": obj2, "relation": rel, "rel_kind": kind}

# numeracy
NUM_WORDS = {
    "one":1, "two":2, "three":3, "four":4, "five":5, "six":6, "seven":7, "eight":8,
    "1":1,"2":2,"3":3,"4":4,"5":5,"6":6,"7":7,"8":8
}
def singularize_basic(noun: str):
    noun = noun.strip(" ,.")
    if noun.endswith("ies"): return noun[:-3] + "y"
    if noun.endswith("es") and len(noun) > 3: return noun[:-2]
    if noun.endswith("s") and len(noun) > 3: return noun[:-1]
    return noun

def parse_numeracy(text: str):
    t = text.lower()
    pairs = re.findall(r"\b(one|two|three|four|five|six|seven|eight|[1-8])\s+([a-zA-Z]+)\b", t)
    if not pairs:
        return {"parseable": 0, "items": []}
    merged = {}
    for num_str, noun in pairs:
        if num_str not in NUM_WORDS:
            continue
        n = NUM_WORDS[num_str]
        obj = singularize_basic(noun)
        merged[obj] = merged.get(obj, 0) + n
    items = [{"obj": k, "count": v} for k,v in merged.items()]
    return {"parseable": 1 if items else 0, "items": items}

# complex noun extraction baseline
STOP = set(["a","an","the","and","with","in","on","of","to","were","was","is","are"])
ADJ = set(["big","small","tall","short","wooden","metal","plastic","round","square","striped","shiny"])

def extract_candidate_nouns_complex(text: str, max_nouns=4):
    t = text.lower()
    t = re.sub(rf"\b{COLOR_WORDS}\b", " ", t)
    words = re.findall(r"[a-z]+", t)
    nouns = []
    for w in words:
        if w in STOP or w in ADJ:
            continue
        if w in NUM_WORDS:
            continue
        nouns.append(singularize_basic(w))
        if len(nouns) >= max_nouns:
            break
    seen=set(); out=[]
    for n in nouns:
        if n not in seen:
            out.append(n); seen.add(n)
    return out

## 5. Step 2 — Object Detection and Coarse Proxy Labels

Step 2 provides the first automatic extraction layer using **OWL-ViT**, an open-vocabulary object detector.

Given a generated image and the prompt-derived object names, Step 2 detects candidate objects and builds coarse proxy labels based on:
- object presence,
- bounding-box geometry for spatial relations,
- and detected object counts for numeracy.

This stage is intentionally simple and serves as the baseline extraction pipeline.  
Later, Step 3 refines these signals using segmentation.

## 6. OWL-ViT Detection Model

This section loads **OWL-ViT**, which is used as the open-vocabulary detector in Step 2.

OWL-ViT is particularly useful in this project because benchmark prompts contain a wide variety of objects, and the detector must respond to object names derived directly from the prompts rather than from a fixed closed class vocabulary.

In [ ]:
from transformers import OwlViTProcessor, OwlViTForObjectDetection
import torch
from PIL import Image

def load_owlvit():
    clear_vram()
    name = "google/owlvit-base-patch32"
    proc = OwlViTProcessor.from_pretrained(name)
    model = OwlViTForObjectDetection.from_pretrained(name).to(DEVICE).eval()
    print("Loaded OWL-ViT:", name)
    return proc, model

@torch.inference_mode()
def owl_detect(proc, model, image: Image.Image, queries, score_thresh=0.10):
    """
    Returns dict: query -> list of (box_xyxy, score), sorted by score desc.
    Compatible with Transformers 5.x OWL-ViT API via post_process_grounded_object_detection.
    """
    # OWL-ViT expects text labels as a batch
    text_labels = [list(queries)]  # batch size = 1

    inputs = proc(text=text_labels, images=image, return_tensors="pt").to(DEVICE)
    outputs = model(**inputs)

    target_sizes = torch.tensor([(image.height, image.width)], device=DEVICE)

    # Transformers 5.x: grounded post-process
    if hasattr(proc, "post_process_grounded_object_detection"):
        results = proc.post_process_grounded_object_detection(
            outputs=outputs,
            target_sizes=target_sizes,
            threshold=score_thresh,
            text_labels=text_labels,
        )[0]
        boxes = results["boxes"].detach().cpu().numpy()
        scores = results["scores"].detach().cpu().numpy()
        pred_labels = results["text_labels"]  # strings (the matched query text)
    else:
        # Fallback (older versions)
        results = proc.post_process_object_detection(
            outputs=outputs,
            target_sizes=target_sizes,
            threshold=score_thresh,
        )[0]
        boxes = results["boxes"].detach().cpu().numpy()
        scores = results["scores"].detach().cpu().numpy()
        label_ids = results["labels"].detach().cpu().numpy()
        pred_labels = [queries[int(i)] for i in label_ids]

    out = {q: [] for q in queries}
    for b, s, lab in zip(boxes, scores, pred_labels):
        lab = str(lab)
        if lab in out:
            out[lab].append((b.tolist(), float(s)))

    for q in queries:
        out[q].sort(key=lambda x: x[1], reverse=True)

    return out

## 7. Bounding-Box-Based Spatial Reasoning

Once objects are detected, their bounding boxes are used as a coarse spatial signal.

For 2D relations, this notebook estimates relative position from bounding-box centers.  
Examples include:
- left/right,
- top/bottom,
- near,
- and side-by-side relations.

This forms the initial relation proxy used in Step 2.

In [ ]:

def box_center_xy(box):
    x1,y1,x2,y2 = box
    return (0.5*(x1+x2), 0.5*(y1+y2))

def check_2d_relation_from_boxes(rel, box1, box2, img_w, img_h):
    c1x,c1y = box_center_xy(box1)
    c2x,c2y = box_center_xy(box2)

    if rel == "left_of":   return int(c1x < c2x)
    if rel == "right_of":  return int(c1x > c2x)
    if rel == "top_of":    return int(c1y < c2y)
    if rel == "bottom_of": return int(c1y > c2y)

    if rel in ["next_to","side_of"]:
        return int(abs(c1x - c2x) / max(img_w,1) < 0.25)

    if rel == "near":
        dx = (c1x - c2x)/max(img_w,1)
        dy = (c1y - c2y)/max(img_h,1)
        return int(math.sqrt(dx*dx + dy*dy) < 0.30)

    return 0

## 8. Step 2 Extraction Loop

This section applies the Step 2 extraction pipeline to all generated images.

For each image, the notebook:
1. parses the prompt,
2. detects target objects using OWL-ViT,
3. records bounding boxes and confidence scores,
4. computes coarse presence, relation, and numeracy proxies,
5. and stores the results in a structured CSV file.

The output of this stage is saved as:
`auto_labels_step2_bbox.csv`

In [ ]:
STEP2_OUT = os.path.join(DIR_TABLES, "auto_labels_step2_bbox.csv")

def run_step2(master_df: pd.DataFrame, out_csv=STEP2_OUT, limit=None, save_every=200):
    done=set(); rows=[]
    if os.path.exists(out_csv):
        prev = pd.read_csv(out_csv)
        rows = prev.to_dict("records")
        done = set(zip(prev["prompt_id"], prev["gen_model"], prev["seed"]))
        print(f"[RESUME] loaded {len(prev)} rows from {out_csv}")

    proc, model = load_owlvit()
    df = master_df.head(limit) if limit is not None else master_df
    new=0

    for _, r in df.iterrows():
        key = (r["prompt_id"], r["gen_model"], int(r["seed"]))
        if key in done:
            continue

        split = r["split"]; text=r["text"]; img_path=r["image_path"]
        rec = dict(
            prompt_id=r["prompt_id"], split=split, gen_model=r["gen_model"], seed=int(r["seed"]),
            image_path=img_path, text=text,
            task=None,
            parseable=0,
            obj1=None, obj2=None, relation=None, rel_kind=None,
            box1=None, box2=None, score1=None, score2=None,
            auto_exist_bbox=0,
            auto_spatial_bbox=None,
            num_items_json=None,
            auto_numeracy_bbox=None,
            objects_json=None,
            auto_exist_all_bbox=None,
        )

        if not os.path.exists(img_path):
            rows.append(rec); done.add(key); continue

        img = Image.open(img_path).convert("RGB")
        w,h = img.size

        # spatial + 3d_spatial
        if split in ["spatial", "3d_spatial"]:
            parsed = parse_two_object_relation(text)
            rec["task"] = "spatial" if parsed.get("rel_kind")=="2d" else "3d_spatial"
            rec["parseable"] = int(parsed.get("parseable", 0))
            rec["obj1"] = parsed.get("obj1"); rec["obj2"] = parsed.get("obj2")
            rec["relation"] = parsed.get("relation"); rec["rel_kind"] = parsed.get("rel_kind")

            if rec["parseable"] == 1:
                det = owl_detect(proc, model, img, [rec["obj1"], rec["obj2"]], score_thresh=0.10)
                cand1 = det[rec["obj1"]][:1]
                cand2 = det[rec["obj2"]][:1]
                if cand1 and cand2:
                    b1,s1 = cand1[0]; b2,s2 = cand2[0]
                    rec["auto_exist_bbox"]=1
                    rec["box1"]=json.dumps(b1); rec["box2"]=json.dumps(b2)
                    rec["score1"]=float(s1); rec["score2"]=float(s2)
                    if rec["rel_kind"]=="2d":
                        rec["auto_spatial_bbox"]=check_2d_relation_from_boxes(rec["relation"], b1,b2,w,h)
                    else:
                        rec["auto_spatial_bbox"]=None  # 3D later via SAM3 proxy

        # numeracy
        elif split == "numeracy":
            parsed = parse_numeracy(text)
            rec["task"]="numeracy"
            rec["parseable"]=int(parsed.get("parseable", 0))
            items = parsed.get("items", [])
            rec["num_items_json"]=json.dumps(items)

            if rec["parseable"]==1 and items:
                objs=[it["obj"] for it in items]
                det = owl_detect(proc, model, img, objs, score_thresh=0.10)
                ok=True
                for it in items:
                    obj=it["obj"]; target=it["count"]
                    found = det.get(obj, [])
                    c = min(len(found), 50)
                    if c != target:
                        ok=False
                rec["auto_exist_bbox"]=1
                rec["auto_numeracy_bbox"]=int(ok)

        # complex
        elif split == "complex":
            rec["task"]="complex"
            nouns = extract_candidate_nouns_complex(text, max_nouns=4)
            rec["objects_json"]=json.dumps(nouns)

            if nouns:
                det = owl_detect(proc, model, img, nouns, score_thresh=0.10)
                exist_flags = {n:(len(det.get(n,[]))>0) for n in nouns}
                rec["auto_exist_bbox"]=int(any(exist_flags.values()))
                rec["auto_exist_all_bbox"]=int(all(exist_flags.values()))

            parsed_rel = parse_two_object_relation(text)
            rel_parseable = int(parsed_rel.get("parseable", 0) and parsed_rel.get("rel_kind")=="2d")
            if rel_parseable==1:
                rec["parseable"]=1
                rec["obj1"]=parsed_rel["obj1"]; rec["obj2"]=parsed_rel["obj2"]
                rec["relation"]=parsed_rel["relation"]; rec["rel_kind"]="2d"
                det2 = owl_detect(proc, model, img, [rec["obj1"], rec["obj2"]], score_thresh=0.10)
                cand1 = det2[rec["obj1"]][:1]
                cand2 = det2[rec["obj2"]][:1]
                if cand1 and cand2:
                    b1,s1=cand1[0]; b2,s2=cand2[0]
                    rec["auto_exist_bbox"]=1
                    rec["box1"]=json.dumps(b1); rec["box2"]=json.dumps(b2)
                    rec["score1"]=float(s1); rec["score2"]=float(s2)
                    rec["auto_spatial_bbox"]=check_2d_relation_from_boxes(rec["relation"], b1,b2,w,h)

        else:
            rec["task"]="unknown"

        rows.append(rec); done.add(key); new += 1

        if new % save_every == 0:
            pd.DataFrame(rows).to_csv(out_csv, index=False)
            print(f"[CHK] saved {len(rows)} rows -> {out_csv}")

    out_df=pd.DataFrame(rows)
    out_df.to_csv(out_csv, index=False)
    print("✅ Step2 saved:", out_csv, "rows:", len(out_df))

    del model
    clear_vram()
    return out_df

# RUN STEP 2
bbox_df = run_step2(master_df, out_csv=STEP2_OUT, limit=None, save_every=200)
bbox_df.head()

## 9. Inspecting Step 2 Outputs

After Step 2 finishes, we inspect the resulting table to verify that:
- prompt parsing succeeded where expected,
- bounding boxes are stored correctly,
- and coarse proxy labels were computed and saved.

This step provides the first automatic baseline for later comparison with both segmentation refinement and VLM judge results.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import os

DRIVE_ROOT = "/content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding"
DIR_TABLES = os.path.join(DRIVE_ROOT, "tables")

STEP2_OUT = os.path.join(DIR_TABLES, "auto_labels_step2_bbox.csv")
STEP3_OUT = os.path.join(DIR_TABLES, "auto_labels_step3_sam3.csv")

os.makedirs(DIR_TABLES, exist_ok=True)

assert os.path.exists(STEP2_OUT), "Run Step 2 first so auto_labels_step2_bbox.csv exists."
print("STEP2_OUT:", STEP2_OUT)
print("STEP3_OUT:", STEP3_OUT)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
STEP2_OUT: /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/auto_labels_step2_bbox.csv
STEP3_OUT: /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/auto_labels_step3_sam3.csv

## 10. Step 3 — Segmentation Refinement with SAM3

Step 2 uses coarse bounding boxes.  
To obtain a more precise object-level signal, Step 3 refines these detections using **SAM3**.

SAM3 is used to convert object proposals into segmentation masks, which provide:
- pixel-level object regions,
- more accurate 2D centroids,
- mask overlap,
- and visibility estimates for occlusion-based reasoning.

This refinement step is especially important for:
- more precise 2D spatial reasoning,
- 3D occlusion-based proxy construction,
- and instance-level refinement for numeracy.

In [ ]:
!pip uninstall -y numpy pandas
!pip install numpy==1.26.4 pandas==2.2.2

Found existing installation: numpy 2.0.2
Uninstalling numpy-2.0.2:
  Successfully uninstalled numpy-2.0.2
Found existing installation: pandas 2.2.2
Uninstalling pandas-2.2.2:
  Successfully uninstalled pandas-2.2.2
Collecting numpy==1.26.4
  Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 3.3 MB/s eta 0:00:00
Collecting pandas==2.2.2
  Downloading pandas-2.2.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (19 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas==2.2.2) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas==2.2.2) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas==2.2.2) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas==2.2.2) (1.17.0)
Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 95.3 MB/s eta 0:00:00
Downloading pandas-2.2.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.7/12.7 MB 102.7 MB/s eta 0:00:00
Installing collected packages: numpy, pandas
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cupy-cuda12x 14.0.1 requires numpy<2.6,>=2.0, but you have numpy 1.26.4 which is incompatible.
xarray-einstats 0.10.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
rasterio 1.5.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
tobler 0.13.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
pytensor 2.38.1 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
jaxlib 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
opencv-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
shap 0.51.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
Successfully installed numpy-1.26.4 pandas-2.2.2

In [ ]:
!python --version
!nvidia-smi

Python 3.12.12
Wed Mar 11 23:33:45 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA L4                      Off |   00000000:00:03.0 Off |                    0 |
| N/A   48C    P8             17W /   72W |       0MiB /  23034MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

## 11. Loading SAM3 from the Official Repository

This section loads **SAM3** using the official repository and checkpoint.  
Because SAM3 is not used through a standard `transformers` interface in this notebook, the official repository is cloned and installed directly inside the Colab environment.

The model is then initialized with the required tokenizer and checkpoint files before inference begins.

In [ ]:
!pip -q install -U huggingface_hub
!git clone https://github.com/facebookresearch/sam3.git
%cd sam3
!pip -q install -e .
!pip -q install -e ".[notebooks]"
%cd /content

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 612.9/612.9 kB 16.4 MB/s eta 0:00:00
Cloning into 'sam3'...
remote: Enumerating objects: 921, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 921 (delta 8), reused 3 (delta 3), pack-reused 904 (from 2)
Receiving objects: 100% (921/921), 59.48 MiB | 27.40 MiB/s, done.
Resolving deltas: 100% (186/186), done.
/content/sam3
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 3.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.2/42.2 kB 5.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.1/53.1 kB 6.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 139.4 MB/s eta 0:00:00
  Building editable for sam3 (pyproject.toml) ... done
  Building wheel for iopath (setup.py) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cupy-cuda12x 14.0.1 requires numpy<2.6,>=2.0, but you have numpy 1.26.4 which is incompatible.
xarray-einstats 0.10.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
rasterio 1.5.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
tobler 0.13.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
pytensor 2.38.1 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
jaxlib 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
opencv-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
shap 0.51.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.6/13.6 MB 152.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.0/143.0 kB 18.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 519.0/519.0 kB 54.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.0/63.0 MB 38.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.4/12.4 MB 157.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 90.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.7/76.7 kB 10.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.8/59.8 kB 7.9 MB/s eta 0:00:00
  Building editable for sam3 (pyproject.toml) ... done
/content

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

In [ ]:
from huggingface_hub import notebook_login
notebook_login()

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [ ]:
import gc
import os
import json
import math
import numpy as np
import pandas as pd
from PIL import Image
import torch

from sam3.model_builder import build_sam3_image_model
from sam3.model.sam3_image_processor import Sam3Processor

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print("DEVICE:", DEVICE)

def clear_vram():
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
        torch.cuda.ipc_collect()

step2_df = pd.read_csv(STEP2_OUT)
print("Step2 rows:", len(step2_df))
step2_df.head()

DEVICE: cuda
Step2 rows: 7200

,prompt_id,split,gen_model,seed,image_path,text,task,parseable,obj1,obj2,...,box1,box2,score1,score2,auto_exist_bbox,auto_spatial_bbox,num_items_json,auto_numeracy_bbox,objects_json,auto_exist_all_bbox
0,complex_000000,complex,flux,0,/content/drive/MyDrive/Vision_Language_Models_...,The red hat was on top of the brown coat rack.,complex,0,NaN,NaN,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,"[""hat"", ""top"", ""coat"", ""rack""]",0.0
1,complex_000000,complex,flux,1,/content/drive/MyDrive/Vision_Language_Models_...,The red hat was on top of the brown coat rack.,complex,0,NaN,NaN,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,"[""hat"", ""top"", ""coat"", ""rack""]",0.0
2,complex_000000,complex,flux,2,/content/drive/MyDrive/Vision_Language_Models_...,The red hat was on top of the brown coat rack.,complex,0,NaN,NaN,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,"[""hat"", ""top"", ""coat"", ""rack""]",0.0
3,complex_000001,complex,flux,0,/content/drive/MyDrive/Vision_Language_Models_...,The blue water bottle was on top of the red ba...,complex,0,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,"[""water"", ""bottle"", ""top"", ""backpack""]",0.0
4,complex_000001,complex,flux,1,/content/drive/MyDrive/Vision_Language_Models_...,The blue water bottle was on top of the red ba...,complex,0,NaN,NaN,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,"[""water"", ""bottle"", ""top"", ""backpack""]",0.0

In [ ]:
import os
from huggingface_hub import hf_hub_download
from sam3.model_builder import build_sam3_image_model
from sam3.model.sam3_image_processor import Sam3Processor

clear_vram()

# local path to the tokenizer vocab inside the cloned repo
BPE_PATH = "/content/sam3/sam3/assets/bpe_simple_vocab_16e6.txt.gz"
assert os.path.exists(BPE_PATH), f"BPE file not found: {BPE_PATH}"

# download checkpoint from Hugging Face
CKPT_PATH = hf_hub_download(
    repo_id="facebook/sam3",
    filename="sam3.pt"
)

print("BPE_PATH:", BPE_PATH)
print("CKPT_PATH:", CKPT_PATH)

model = build_sam3_image_model(
    bpe_path=BPE_PATH,
    checkpoint_path=CKPT_PATH,
    load_from_HF=False,
    device=DEVICE,
)

processor = Sam3Processor(model)

print("SAM3 loaded successfully.")

sam3.pt:   0%|          | 0.00/3.45G [00:00<?, ?B/s]

BPE_PATH: /content/sam3/sam3/assets/bpe_simple_vocab_16e6.txt.gz
CKPT_PATH: /root/.cache/huggingface/hub/models--facebook--sam3/snapshots/3c879f39826c281e95690f02c7821c4de09afae7/sam3.pt
SAM3 loaded successfully.

## 12. From Bounding Boxes to Segmentation Masks

This section defines helper functions that use SAM3 to convert bounding-box detections into segmentation masks.

These masks are later used to compute:
- object centroids,
- 2D relative position,
- overlap and visible area,
- and 3D occlusion-based proxy signals.

In [ ]:
def sam3_mask_from_box(image_pil, box_xyxy):

    inference_state = processor.set_image(image_pil)

    x1, y1, x2, y2 = box_xyxy

    output = processor.add_geometric_prompt(
        state=inference_state,
        box=[x1, y1, x2, y2],
        label=1
    )

    masks = output["masks"]
    scores = output["scores"]

    if masks is None or len(masks) == 0:
        return None, None

    if torch.is_tensor(scores):
        scores = scores.detach().cpu().numpy()

    best_idx = int(np.argmax(scores))

    mask = masks[best_idx]
    score = float(scores[best_idx])

    if torch.is_tensor(mask):
        mask = mask.detach().cpu().numpy()

    mask = np.array(mask)
    mask = np.squeeze(mask)

    if mask.ndim == 3:
        mask = mask[0]

    mask = (mask > 0).astype(np.uint8)

    return mask, score

## 13. Pixel-Level Spatial and Occlusion Reasoning

With segmentation masks available, spatial reasoning can be performed directly on object pixels rather than on coarse bounding boxes.

This section defines:
- centroid-based 2D relation checks,
- overlap and visibility calculations,
- and an occlusion-based proxy for 3D relations such as:
  - *in front of*,
  - *behind*,
  - *hidden by*.

These functions provide the refined proxy labels produced by Step 3.

In [ ]:
def mask_centroid(mask):
    if torch.is_tensor(mask):
        mask = mask.detach().cpu().numpy()

    mask = np.array(mask)

    # remove singleton dimensions like (1,H,W) or (H,W,1)
    mask = np.squeeze(mask)

    # if still 3D, take the first mask
    if mask.ndim == 3:
        mask = mask[0]

    ys, xs = np.where(mask > 0)

    if len(xs) == 0:
        return None

    return float(xs.mean()), float(ys.mean())

def check_2d_relation_from_masks(rel, m1, m2):
    c1 = mask_centroid(m1)
    c2 = mask_centroid(m2)

    if c1 is None or c2 is None:
        return 0

    x1, y1 = c1
    x2, y2 = c2
    H, W = m1.shape

    if rel == "left_of":
        return int(x1 < x2)
    if rel == "right_of":
        return int(x1 > x2)
    if rel == "top_of":
        return int(y1 < y2)
    if rel == "bottom_of":
        return int(y1 > y2)

    if rel in ["next_to", "side_of"]:
        return int(abs(x1 - x2) / max(W, 1) < 0.25)

    if rel == "near":
        dx = (x1 - x2) / max(W, 1)
        dy = (y1 - y2) / max(H, 1)
        return int(math.sqrt(dx * dx + dy * dy) < 0.30)

    return 0


def occlusion_metrics(m1, m2):
    A = m1.astype(bool)
    B = m2.astype(bool)

    inter = (A & B).sum()
    areaA = A.sum() + 1e-6
    areaB = B.sum() + 1e-6

    overlap_ratio = inter / min(areaA, areaB)
    visA = (A & (~B)).sum() / areaA
    visB = (B & (~A)).sum() / areaB

    return float(overlap_ratio), float(visA), float(visB)


def check_3d_relation_from_masks(rel, m1, m2):
    """
    m1 = obj1 mask
    m2 = obj2 mask
    """

    A = m1.astype(bool)
    B = m2.astype(bool)
    inter = (A & B).sum()

    if inter == 0:
        return 0

    areaA = A.sum() + 1e-6
    areaB = B.sum() + 1e-6
    visA = (A & (~B)).sum() / areaA
    visB = (B & (~A)).sum() / areaB
    overlap_ratio = inter / min(areaA, areaB)

    if rel == "in_front_of":
        return int(overlap_ratio > 0.05 and visA > 0.60 and visB < 0.95)

    if rel == "behind":
        return int(overlap_ratio > 0.05 and visB > 0.60 and visA < 0.95)

    if rel == "hidden_by":
        return int(overlap_ratio > 0.05 and visA < 0.35)

    return 0

## 14. Step 3 Refinement Loop

This section applies SAM3 refinement to the Step 2 outputs.

For each image with valid object detections, the notebook:
1. loads the corresponding image,
2. refines the detected objects into segmentation masks,
3. computes pixel-level spatial proxy labels,
4. and stores the results in a new CSV file.

The output of this stage is saved as:
`auto_labels_step3_sam3.csv`

In [ ]:
def run_step3_sam3(step2_df, out_csv=STEP3_OUT, save_every=100, clear_every=25):
    done = set()
    rows = []

    if os.path.exists(out_csv):
        prev = pd.read_csv(out_csv)
        rows = prev.to_dict("records")
        done = set(zip(prev["prompt_id"], prev["gen_model"], prev["seed"]))
        print(f"[RESUME] loaded {len(prev)} rows from existing Step 3 file.")

    new = 0

    for _, r in step2_df.iterrows():
        key = (r["prompt_id"], r["gen_model"], int(r["seed"]))
        if key in done:
            continue

        rec = {
            "prompt_id": r["prompt_id"],
            "split": r["split"],
            "gen_model": r["gen_model"],
            "seed": int(r["seed"]),
            "image_path": r["image_path"],
            "text": r["text"],
            "task": r.get("task", None),
            "parseable": int(r.get("parseable", 0)),
            "obj1": r.get("obj1", None),
            "obj2": r.get("obj2", None),
            "relation": r.get("relation", None),
            "rel_kind": r.get("rel_kind", None),
            "auto_exist_sam3": 0,
            "auto_spatial_sam3": None,
            "sam3_score1": None,
            "sam3_score2": None,
            "overlap_ratio": None,
            "vis1": None,
            "vis2": None,
        }

        # Need both boxes from Step 2
        if not isinstance(r.get("box1", None), str) or not isinstance(r.get("box2", None), str):
            rows.append(rec)
            done.add(key)
            continue

        if not os.path.exists(r["image_path"]):
            rows.append(rec)
            done.add(key)
            continue

        box1 = json.loads(r["box1"])
        box2 = json.loads(r["box2"])
        img = Image.open(r["image_path"]).convert("RGB")

        m1, s1 = sam3_mask_from_box(img, box1)
        m2, s2 = sam3_mask_from_box(img, box2)

        if m1 is not None and m2 is not None:
            rec["auto_exist_sam3"] = 1
            rec["sam3_score1"] = s1
            rec["sam3_score2"] = s2

            if rec["rel_kind"] == "2d":
                rec["auto_spatial_sam3"] = check_2d_relation_from_masks(rec["relation"], m1, m2)

            elif rec["rel_kind"] == "3d":
                rec["auto_spatial_sam3"] = check_3d_relation_from_masks(rec["relation"], m1, m2)
                ov, v1, v2 = occlusion_metrics(m1, m2)
                rec["overlap_ratio"] = ov
                rec["vis1"] = v1
                rec["vis2"] = v2

        rows.append(rec)
        done.add(key)
        new += 1

        if new % save_every == 0:
            pd.DataFrame(rows).to_csv(out_csv, index=False)
            print(f"[CHK] saved {len(rows)} rows to {out_csv}")

        if new % clear_every == 0:
            clear_vram()

    out_df = pd.DataFrame(rows)
    out_df.to_csv(out_csv, index=False)
    print("✅ Step 3 finished.")
    print("Saved:", out_csv)
    print("Rows:", len(out_df))
    return out_df

## 15. Step 3 Proxy Summary

After Step 3 finishes, we summarize the resulting proxy signals separately for:
- **2D spatial relations**, and
- **3D spatial relations**.

These summaries provide a refined automatic reference that will later be compared with VLM-as-a-Judge outputs.

In [ ]:
sam3_df = run_step3_sam3(step2_df)
sam3_df.head()

[RESUME] loaded 1643 rows from existing Step 3 file.
[CHK] saved 2813 rows to /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/auto_labels_step3_sam3.csv
[CHK] saved 3097 rows to /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/auto_labels_step3_sam3.csv
[CHK] saved 3377 rows to /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/auto_labels_step3_sam3.csv
[CHK] saved 3722 rows to /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/auto_labels_step3_sam3.csv
[CHK] saved 4726 rows to /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/auto_labels_step3_sam3.csv
[CHK] saved 4945 rows to /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/auto_labels_step3_sam3.csv
[CHK] saved 5187 rows to /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/auto_labels_step3_sam3.csv
[CHK] saved 6353 rows to /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/auto_labels_step3_sam3.csv
[CHK] saved 6607 rows to /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/auto_labels_step3_sam3.csv
[CHK] saved 6827 rows to /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/auto_labels_step3_sam3.csv
[CHK] saved 7060 rows to /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/auto_labels_step3_sam3.csv
✅ Step 3 finished.
Saved: /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/auto_labels_step3_sam3.csv
Rows: 7200

,prompt_id,split,gen_model,seed,image_path,text,task,parseable,obj1,obj2,relation,rel_kind,auto_exist_sam3,auto_spatial_sam3,sam3_score1,sam3_score2,overlap_ratio,vis1,vis2
0,complex_000000,complex,flux,0,/content/drive/MyDrive/Vision_Language_Models_...,The red hat was on top of the brown coat rack.,complex,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
1,complex_000000,complex,flux,1,/content/drive/MyDrive/Vision_Language_Models_...,The red hat was on top of the brown coat rack.,complex,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
2,complex_000000,complex,flux,2,/content/drive/MyDrive/Vision_Language_Models_...,The red hat was on top of the brown coat rack.,complex,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
3,complex_000001,complex,flux,0,/content/drive/MyDrive/Vision_Language_Models_...,The blue water bottle was on top of the red ba...,complex,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
4,complex_000001,complex,flux,1,/content/drive/MyDrive/Vision_Language_Models_...,The blue water bottle was on top of the red ba...,complex,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
print("2D spatial proxy success:")
display(
    sam3_df[sam3_df["rel_kind"] == "2d"]
    .groupby(["split", "gen_model"])["auto_spatial_sam3"]
    .mean()
)

print("3D spatial proxy success:")
display(
    sam3_df[sam3_df["rel_kind"] == "3d"]
    .groupby(["split", "gen_model"])["auto_spatial_sam3"]
    .mean()
)

2D spatial proxy success:

split    gen_model
complex  flux         0.880000
         sdxl         0.857143
spatial  flux         0.618182
         sdxl         0.596817
Name: auto_spatial_sam3, dtype: float64

3D spatial proxy success:

split       gen_model
3d_spatial  flux         0.352239
            sdxl         0.356948
Name: auto_spatial_sam3, dtype: float64

## 16. Reloading Step 3 Outputs from Drive

Because long-running segmentation jobs may require notebook restarts, the saved Step 3 CSV is reloaded from Drive when needed.

This avoids re-running segmentation and makes the workflow more robust across sessions.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
SAM3_PATH = "/content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/auto_labels_step3_sam3.csv"

In [ ]:
import pandas as pd

sam3_df = pd.read_csv(SAM3_PATH)

sam3_df.head()

,prompt_id,split,gen_model,seed,image_path,text,task,parseable,obj1,obj2,relation,rel_kind,auto_exist_sam3,auto_spatial_sam3,sam3_score1,sam3_score2,overlap_ratio,vis1,vis2
0,complex_000000,complex,flux,0,/content/drive/MyDrive/Vision_Language_Models_...,The red hat was on top of the brown coat rack.,complex,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
1,complex_000000,complex,flux,1,/content/drive/MyDrive/Vision_Language_Models_...,The red hat was on top of the brown coat rack.,complex,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
2,complex_000000,complex,flux,2,/content/drive/MyDrive/Vision_Language_Models_...,The red hat was on top of the brown coat rack.,complex,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
3,complex_000001,complex,flux,0,/content/drive/MyDrive/Vision_Language_Models_...,The blue water bottle was on top of the red ba...,complex,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
4,complex_000001,complex,flux,1,/content/drive/MyDrive/Vision_Language_Models_...,The blue water bottle was on top of the red ba...,complex,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
sam3_df[sam3_df["rel_kind"]=="2d"].groupby(["split","gen_model"]).size()
sam3_df[sam3_df["rel_kind"]=="3d"].groupby(["split","gen_model"]).size()

split       gen_model
3d_spatial  flux         900
            sdxl         900
dtype: int64

## 17. Numeracy Refinement

Numeracy requires a different type of evaluation from spatial reasoning.  
Instead of judging relative position, the goal is to determine whether the generated image contains the correct **number of object instances**.

This section builds a numeracy proxy by combining:
- OWL-ViT for object detection,
- SAM3 for mask refinement,
- duplicate suppression and filtering,
- and final soft/exact counting scores.

This produces a numeracy reference signal that can later be compared with VLM judge outputs.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import os
import gc
import json
import math
import numpy as np
import pandas as pd
from PIL import Image
import torch

DRIVE_ROOT = "/content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding"       # change if needed
DIR_TABLES = os.path.join(DRIVE_ROOT, "tables")

STEP2_OUT = os.path.join(DIR_TABLES, "auto_labels_step2_bbox.csv")
assert os.path.exists(STEP2_OUT), f"Missing: {STEP2_OUT}"

step2_df = pd.read_csv(STEP2_OUT)
num_df = step2_df[step2_df["task"] == "numeracy"].copy()

print("Numeracy rows:", len(num_df))
num_df.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Numeracy rows: 1800

,prompt_id,split,gen_model,seed,image_path,text,task,parseable,obj1,obj2,...,box1,box2,score1,score2,auto_exist_bbox,auto_spatial_bbox,num_items_json,auto_numeracy_bbox,objects_json,auto_exist_all_bbox
1800,numeracy_000000,numeracy,flux,0,/content/drive/MyDrive/Vision_Language_Models_...,two boys,numeracy,1,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,"[{""obj"": ""boy"", ""count"": 2}]",1.0,NaN,NaN
1801,numeracy_000000,numeracy,flux,1,/content/drive/MyDrive/Vision_Language_Models_...,two boys,numeracy,1,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,"[{""obj"": ""boy"", ""count"": 2}]",1.0,NaN,NaN
1802,numeracy_000000,numeracy,flux,2,/content/drive/MyDrive/Vision_Language_Models_...,two boys,numeracy,1,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,"[{""obj"": ""boy"", ""count"": 2}]",1.0,NaN,NaN
1803,numeracy_000001,numeracy,flux,0,/content/drive/MyDrive/Vision_Language_Models_...,six airplanes,numeracy,1,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,"[{""obj"": ""airplan"", ""count"": 6}]",0.0,NaN,NaN
1804,numeracy_000001,numeracy,flux,1,/content/drive/MyDrive/Vision_Language_Models_...,six airplanes,numeracy,1,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,"[{""obj"": ""airplan"", ""count"": 6}]",0.0,NaN,NaN

## 18. Numeracy Utilities

This section defines helper functions for numeracy evaluation, including:
- parsing target counts from prompt metadata,
- mask overlap calculations for duplicate suppression,
- and simple geometric utilities required during instance refinement.

In [ ]:
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print("DEVICE:", DEVICE)

def clear_vram():
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
        torch.cuda.ipc_collect()

def mask_iou(m1, m2):
    A = m1.astype(bool)
    B = m2.astype(bool)
    inter = (A & B).sum()
    union = (A | B).sum() + 1e-6
    return float(inter / union)

def box_area(box):
    x1, y1, x2, y2 = box
    return max(0, x2 - x1) * max(0, y2 - y1)

def parse_num_items(num_items_json):
    """
    expects num_items_json like:
    [{"obj": "apple", "count": 3}, {"obj": "knife", "count": 2}]
    """
    try:
        items = json.loads(num_items_json)
    except:
        return []

    clean = []
    for it in items:
        obj = str(it["obj"]).strip().lower()
        cnt = int(it["count"])
        clean.append({"obj": obj, "count": cnt})
    return clean

DEVICE: cuda

## 19. OWL-ViT Detection for Numeracy

For numeracy, the detector is queried with the target object categories extracted from the prompt.  
The resulting detections are later refined with SAM3 so that object counts can be estimated more reliably than with raw bounding boxes alone.

In [ ]:
from transformers import OwlViTProcessor, OwlViTForObjectDetection

def load_owlvit():
    clear_vram()
    name = "google/owlvit-base-patch32"
    proc = OwlViTProcessor.from_pretrained(name)
    model = OwlViTForObjectDetection.from_pretrained(name).to(DEVICE).eval()
    print("Loaded OWL-ViT:", name)
    return proc, model

@torch.inference_mode()
def owl_detect(proc, model, image: Image.Image, queries, score_thresh=0.10):
    text_labels = [list(queries)]
    inputs = proc(text=text_labels, images=image, return_tensors="pt").to(DEVICE)
    outputs = model(**inputs)

    target_sizes = torch.tensor([(image.height, image.width)], device=DEVICE)

    if hasattr(proc, "post_process_grounded_object_detection"):
        results = proc.post_process_grounded_object_detection(
            outputs=outputs,
            target_sizes=target_sizes,
            threshold=score_thresh,
            text_labels=text_labels,
        )[0]
        boxes = results["boxes"].detach().cpu().numpy()
        scores = results["scores"].detach().cpu().numpy()
        pred_labels = results["text_labels"]
    else:
        results = proc.post_process_object_detection(
            outputs=outputs,
            target_sizes=target_sizes,
            threshold=score_thresh,
        )[0]
        boxes = results["boxes"].detach().cpu().numpy()
        scores = results["scores"].detach().cpu().numpy()
        label_ids = results["labels"].detach().cpu().numpy()
        pred_labels = [queries[int(i)] for i in label_ids]

    out = {q: [] for q in queries}
    for b, s, lab in zip(boxes, scores, pred_labels):
        lab = str(lab).lower()
        if lab in out:
            out[lab].append((b.tolist(), float(s)))

    for q in queries:
        out[q].sort(key=lambda x: x[1], reverse=True)

    return out

owl_proc, owl_model = load_owlvit()

preprocessor_config.json:   0%|          | 0.00/392 [00:00<?, ?B/s]

The image processor of type `OwlViTImageProcessor` is now loaded as a fast processor by default, even if the model checkpoint was saved with a slow processor. This is a breaking change and may produce slightly different outputs. To continue using the slow processor, instantiate this class with `use_fast=False`.

config.json: 0.00B [00:00, ?B/s]

tokenizer_config.json:   0%|          | 0.00/775 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/460 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/613M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/412 [00:00<?, ?it/s]

OwlViTForObjectDetection LOAD REPORT from: google/owlvit-base-patch32
Key                                         | Status     |  |
--------------------------------------------+------------+--+-
owlvit.text_model.embeddings.position_ids   | UNEXPECTED |  |
owlvit.vision_model.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loaded OWL-ViT: google/owlvit-base-patch32

In [ ]:
assert "processor" in globals(), "SAM3 processor not found. Load SAM3 first."

In [ ]:
def sam3_mask_from_box(image_pil, box_xyxy):
    inference_state = processor.set_image(image_pil)

    x1, y1, x2, y2 = box_xyxy

    output = processor.add_geometric_prompt(
        state=inference_state,
        box=[x1, y1, x2, y2],
        label=1
    )

    masks = output["masks"]
    scores = output["scores"]

    if masks is None or len(masks) == 0:
        return None, None

    if torch.is_tensor(scores):
        scores = scores.detach().cpu().numpy()

    best_idx = int(np.argmax(scores))

    mask = masks[best_idx]
    score = float(scores[best_idx])

    if torch.is_tensor(mask):
        mask = mask.detach().cpu().numpy()

    mask = np.array(mask)
    mask = np.squeeze(mask)

    if mask.ndim == 3:
        mask = mask[0]

    mask = (mask > 0).astype(np.uint8)

    return mask, score

## 20. Instance Refinement for Counting

This section refines detector outputs into segmentation masks and filters them to improve counting quality.

The main goals are to:
- remove tiny or spurious detections,
- suppress duplicated detections,
- and count the remaining instance masks as candidate objects.

This refined instance count is then compared with the prompt target counts.

In [ ]:
def refine_and_count_object_instances(image_pil, boxes_scores,
                                      min_mask_area_ratio=0.0005,
                                      iou_dup_thresh=0.6):
    """
    boxes_scores: list of (box, score) for one object class
    returns:
      kept_masks, kept_boxes, kept_scores
    """
    W, H = image_pil.size
    img_area = W * H

    candidates = []

    for box, det_score in boxes_scores:
        if box_area(box) <= 1:
            continue

        mask, sam_score = sam3_mask_from_box(image_pil, box)
        if mask is None:
            continue

        # remove tiny masks
        area = mask.sum()
        if area < min_mask_area_ratio * img_area:
            continue

        candidates.append({
            "box": box,
            "det_score": float(det_score),
            "sam_score": float(sam_score),
            "mask": mask,
            "area": float(area),
        })

    # sort by combined confidence
    candidates.sort(key=lambda x: (x["det_score"] + x["sam_score"]), reverse=True)

    kept = []
    for c in candidates:
        duplicate = False
        for k in kept:
            if mask_iou(c["mask"], k["mask"]) > iou_dup_thresh:
                duplicate = True
                break
        if not duplicate:
            kept.append(c)

    kept_masks = [k["mask"] for k in kept]
    kept_boxes = [k["box"] for k in kept]
    kept_scores = [k["det_score"] + k["sam_score"] for k in kept]

    return kept_masks, kept_boxes, kept_scores

## 21. Numeracy Scoring

Two numeracy scores are computed:

- **Exact score**: whether all target counts are exactly correct.
- **Soft score**: a partial-credit metric that rewards approximate correctness even when the counts are not exact.

Using both metrics provides a more informative view of counting performance than an exact-match score alone.

In [ ]:
def numeracy_soft_score(target_items, pred_counts):
    """
    target_items: [{"obj":..., "count":...}, ...]
    pred_counts: {"apple":2, "knife":1, ...}
    """
    scores = []
    for it in target_items:
        obj = it["obj"]
        target = int(it["count"])
        pred = int(pred_counts.get(obj, 0))
        scores.append(min(pred, target) / max(target, 1))
    if len(scores) == 0:
        return 0.0
    return float(np.mean(scores))

def numeracy_exact_score(target_items, pred_counts):
    for it in target_items:
        obj = it["obj"]
        target = int(it["count"])
        pred = int(pred_counts.get(obj, 0))
        if pred != target:
            return 0.0
    return 1.0

## 22. Numeracy Evaluation Loop

This section applies the numeracy pipeline to all numeracy images.

For each image, the notebook:
1. reads the target object counts,
2. detects the requested object categories,
3. refines detections into instance masks,
4. counts the final instances,
5. computes exact and soft numeracy scores,
6. and saves the results to a CSV file.

The output is saved as:
`auto_labels_numeracy_sam3_refined.csv`

In [ ]:
NUMERACY_REFINED_OUT = os.path.join(DIR_TABLES, "auto_labels_numeracy_sam3_refined.csv")

def run_numeracy_with_sam3(num_df, out_csv=NUMERACY_REFINED_OUT,
                           owl_thresh=0.10,
                           save_every=50,
                           clear_every=20):
    done = set()
    rows = []

    if os.path.exists(out_csv):
        prev = pd.read_csv(out_csv)
        rows = prev.to_dict("records")
        done = set(zip(prev["prompt_id"], prev["gen_model"], prev["seed"]))
        print(f"[RESUME] loaded {len(prev)} rows")

    new = 0

    for _, r in num_df.iterrows():
        key = (r["prompt_id"], r["gen_model"], int(r["seed"]))
        if key in done:
            continue

        rec = {
            "prompt_id": r["prompt_id"],
            "split": r["split"],
            "gen_model": r["gen_model"],
            "seed": int(r["seed"]),
            "image_path": r["image_path"],
            "text": r["text"],
            "num_items_json": r.get("num_items_json", None),
            "pred_counts_json": None,
            "numeracy_score_soft": 0.0,
            "numeracy_score_exact": 0.0,
        }

        if not os.path.exists(r["image_path"]):
            rows.append(rec)
            done.add(key)
            continue

        target_items = parse_num_items(r["num_items_json"])
        if len(target_items) == 0:
            rows.append(rec)
            done.add(key)
            continue

        image_pil = Image.open(r["image_path"]).convert("RGB")
        queries = [it["obj"] for it in target_items]

        # detect target objects
        det = owl_detect(owl_proc, owl_model, image_pil, queries, score_thresh=owl_thresh)

        pred_counts = {}

        for obj in queries:
            boxes_scores = det.get(obj, [])
            kept_masks, kept_boxes, kept_scores = refine_and_count_object_instances(
                image_pil,
                boxes_scores,
                min_mask_area_ratio=0.0005,
                iou_dup_thresh=0.6
            )
            pred_counts[obj] = len(kept_masks)

        rec["pred_counts_json"] = json.dumps(pred_counts)
        rec["numeracy_score_soft"] = numeracy_soft_score(target_items, pred_counts)
        rec["numeracy_score_exact"] = numeracy_exact_score(target_items, pred_counts)

        rows.append(rec)
        done.add(key)
        new += 1

        if new % save_every == 0:
            pd.DataFrame(rows).to_csv(out_csv, index=False)
            print(f"[CHK] saved {len(rows)} rows")

        if new % clear_every == 0:
            clear_vram()

    out_df = pd.DataFrame(rows)
    out_df.to_csv(out_csv, index=False)
    print("Saved:", out_csv, "rows:", len(out_df))
    return out_df

In [ ]:
num_sam3_df = run_numeracy_with_sam3(num_df)
num_sam3_df.head()

[RESUME] loaded 1750 rows
[CHK] saved 1800 rows
Saved: /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/auto_labels_numeracy_sam3_refined.csv rows: 1800

,prompt_id,split,gen_model,seed,image_path,text,num_items_json,pred_counts_json,numeracy_score_soft,numeracy_score_exact
0,numeracy_000000,numeracy,flux,0,/content/drive/MyDrive/Vision_Language_Models_...,two boys,"[{""obj"": ""boy"", ""count"": 2}]","{""boy"": 1}",0.5,0.0
1,numeracy_000000,numeracy,flux,1,/content/drive/MyDrive/Vision_Language_Models_...,two boys,"[{""obj"": ""boy"", ""count"": 2}]","{""boy"": 1}",0.5,0.0
2,numeracy_000000,numeracy,flux,2,/content/drive/MyDrive/Vision_Language_Models_...,two boys,"[{""obj"": ""boy"", ""count"": 2}]","{""boy"": 1}",0.5,0.0
3,numeracy_000001,numeracy,flux,0,/content/drive/MyDrive/Vision_Language_Models_...,six airplanes,"[{""obj"": ""airplan"", ""count"": 6}]","{""airplan"": 0}",0.0,0.0
4,numeracy_000001,numeracy,flux,1,/content/drive/MyDrive/Vision_Language_Models_...,six airplanes,"[{""obj"": ""airplan"", ""count"": 6}]","{""airplan"": 0}",0.0,0.0

## 23. Numeracy Summary

Finally, the numeracy scores are aggregated by generator model.  
This provides a compact comparison of how well each image-generation model satisfies object-count constraints in the benchmark prompts.

In [ ]:
numeracy_summary = (
    num_sam3_df.groupby(["split", "gen_model"])[["numeracy_score_soft", "numeracy_score_exact"]]
    .mean()
    .reset_index()
)

numeracy_summary

      split gen_model  numeracy_score_soft  numeracy_score_exact
0  numeracy      flux             0.277427              0.027778
1  numeracy      sdxl             0.269419              0.024444

## 24. Summary of This Notebook

In this notebook, we constructed the **automatic extraction and proxy ground-truth pipeline** for the generated images.

The notebook produced:
- a **Step 2 detection-based baseline** using OWL-ViT,
- a **Step 3 segmentation-refined spatial proxy** using SAM3,
- and a **numeracy refinement pipeline** combining detection and segmentation.

These outputs provide automatic reference signals for:
- object presence,
- 2D spatial correctness,
- 3D occlusion-based spatial correctness,
- and object counting.

In the next notebook, these proxy labels will be compared with **VLM-as-a-Judge** scores in order to evaluate whether multimodal language models can serve as reliable judges of diffusion-model compositional failures.