# Vision-Language Models for Spatial Understanding  
## Notebook 3 — VLM-as-a-Judge Evaluation

### Mehregan Nazarmohsenifakori

This notebook implements the **VLM-as-a-Judge stage** of the project.

## Project Role of This Notebook
The goal of this project is to evaluate whether **Vision-Language Models (VLMs)** can serve as reliable judges of compositional failures in text-to-image generation.

In the previous notebooks:
- Notebook 1 generated images using diffusion models,
- Notebook 2 built automatic proxy labels using detection, segmentation, and counting.

This notebook introduces a complementary evaluation pipeline in which multimodal language models are asked to judge whether:
1. the required objects described in the prompt are present in the generated image,
2. the required relations, counts, or overall composition are correct.

## Why VLM-as-a-Judge?
Automatic proxy labels are useful but imperfect.  
They depend on the quality of detection, segmentation, and prompt parsing, and may fail even when the generated image is visually correct.

For this reason, this notebook evaluates generated images with **independent Vision-Language Model judges** that receive only:
- the generated image,
- and the original prompt.

The goal is to compare VLM judgments against the proxy pipeline and analyze whether VLMs can serve as a meaningful evaluation signal for compositional image generation.

## Judge Models Used
This notebook evaluates multiple VLM judges:
- **Qwen2.5-VL**
- **Qwen3-VL**
- **Gemma 3** (if access is available)

These models are tested using multiple prompt variants and later compared in the analysis notebook.

## 1. Google Drive Setup and Input Tables

This section mounts Google Drive and defines the input files required for VLM evaluation.

The notebook reads:
- the **master image index** from Notebook 1,
- the **Step 2 proxy labels** from detection,
- the **Step 3 proxy labels** from segmentation-based refinement,
- and the **numeracy refinement results**.

These tables are merged into a unified evaluation dataframe that will later be compared with the outputs of the VLM judges.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import os

DRIVE_ROOT = "/content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding"
DIR_TABLES = os.path.join(DRIVE_ROOT, "tables")

MASTER_CSV = os.path.join(DIR_TABLES, "master_generated_index.csv")
STEP2_CSV = os.path.join(DIR_TABLES, "auto_labels_step2_bbox.csv")
STEP3_CSV = os.path.join(DIR_TABLES, "auto_labels_step3_sam3.csv")
NUM_CSV = os.path.join(DIR_TABLES, "auto_labels_numeracy_sam3_refined.csv")

assert os.path.exists(MASTER_CSV), MASTER_CSV
assert os.path.exists(STEP2_CSV), STEP2_CSV
assert os.path.exists(STEP3_CSV), STEP3_CSV
assert os.path.exists(NUM_CSV), NUM_CSV

print("Paths OK.")

Mounted at /content/drive
Paths OK.

## 2. Environment Setup

This section installs the dependencies required for multimodal model inference.

The main libraries used in this notebook are:
- `transformers` for loading VLM judges,
- `torch` for GPU inference,
- `pandas` and `numpy` for data processing,
- and `scipy` for correlation analysis.

The notebook is designed for execution in **Google Colab with GPU support**.

In [ ]:
!pip -q install -U "transformers>=5.2.0" accelerate scipy "pillow<12.0"

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.1/62.1 kB 6.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 134.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.2/35.2 MB 73.2 MB/s eta 0:00:00

## 3. Imports, Device Configuration, and Utility Functions

This section imports the required libraries, sets the computation device, and defines helper functions for memory management.

Because multimodal VLMs are large and memory-intensive, GPU memory is cleared between runs to keep the notebook stable during long evaluation loops.

In [ ]:
import gc
import os
import re
import json
import math
import numpy as np
import pandas as pd
from PIL import Image

import torch
from scipy.stats import spearmanr

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
DTYPE = torch.bfloat16 if DEVICE == "cuda" else torch.float32

print("DEVICE:", DEVICE)
print("DTYPE:", DTYPE)

def clear_vram():
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
        torch.cuda.ipc_collect()

DEVICE: cuda
DTYPE: torch.bfloat16

## 4. Loading and Merging Evaluation Tables

This section loads the outputs from the previous notebooks and merges them into a unified evaluation dataframe.

The merged table contains:
- prompt identifiers,
- split labels,
- generator model names,
- seeds,
- image paths,
- original prompt text,
- automatic presence and relation proxies,
- and numeracy scores.

This unified table becomes the central input for the VLM judge pipeline.

In [ ]:
master_df = pd.read_csv(MASTER_CSV)
step2_df = pd.read_csv(STEP2_CSV)
step3_df = pd.read_csv(STEP3_CSV)
num_df = pd.read_csv(NUM_CSV)

# normalize split names
def norm_split(s):
    s = str(s).strip().lower()
    if s in ["3dspatial", "3d_spatial", "3d-spatial"]:
        return "3d_spatial"
    if s in ["numeric", "numeracy"]:
        return "numeracy"
    return s

for df in [master_df, step2_df, step3_df, num_df]:
    if "split" in df.columns:
        df["split"] = df["split"].apply(norm_split)

key_cols = ["prompt_id", "gen_model", "seed"]


step2_keep = step2_df[key_cols + [
    "task", "parseable", "obj1", "obj2", "relation", "rel_kind",
    "auto_exist_bbox", "auto_spatial_bbox", "num_items_json", "objects_json"
]].copy()

step3_keep = step3_df[key_cols + [
    "auto_exist_sam3", "auto_spatial_sam3"
]].copy()

num_keep = num_df[key_cols + [
    "numeracy_score_soft", "numeracy_score_exact", "pred_counts_json", "num_items_json"
]].copy()

eval_df = master_df.merge(step2_keep, on=key_cols, how="left")
eval_df = eval_df.merge(step3_keep, on=key_cols, how="left")
eval_df = eval_df.merge(num_keep, on=key_cols, how="left", suffixes=("", "_num"))

# proxy GT columns
def compute_gt_presence(row):
    split = row["split"]
    if split == "numeracy":
        # weak presence proxy: at least some target object evidence
        return 1.0 if float(row.get("numeracy_score_soft", 0) or 0) > 0 else 0.0
    # prefer SAM3 presence, fallback to bbox
    if pd.notna(row.get("auto_exist_sam3")):
        return float(row["auto_exist_sam3"])
    if pd.notna(row.get("auto_exist_bbox")):
        return float(row["auto_exist_bbox"])
    return np.nan

def compute_gt_relation(row):
    split = row["split"]
    if split == "numeracy":
        return float(row.get("numeracy_score_soft", 0) or 0)
    if pd.notna(row.get("auto_spatial_sam3")):
        return float(row["auto_spatial_sam3"])
    if pd.notna(row.get("auto_spatial_bbox")):
        return float(row["auto_spatial_bbox"])
    return np.nan

eval_df["gt_presence_proxy"] = eval_df.apply(compute_gt_presence, axis=1)
eval_df["gt_relation_proxy"] = eval_df.apply(compute_gt_relation, axis=1)

print("rows:", len(eval_df))
eval_df.head()

rows: 7200

,prompt_id,split,text,gen_model,seed,image_path,source_csv,task,parseable,obj1,...,num_items_json,objects_json,auto_exist_sam3,auto_spatial_sam3,numeracy_score_soft,numeracy_score_exact,pred_counts_json,num_items_json_num,gt_presence_proxy,gt_relation_proxy
0,complex_000000,complex,The red hat was on top of the brown coat rack.,flux,0,/content/drive/MyDrive/Vision_Language_Models_...,generated_index_flux_complex_3seeds.csv,complex,0,NaN,...,NaN,"[""hat"", ""top"", ""coat"", ""rack""]",0,NaN,NaN,NaN,NaN,NaN,0.0,NaN
1,complex_000000,complex,The red hat was on top of the brown coat rack.,flux,1,/content/drive/MyDrive/Vision_Language_Models_...,generated_index_flux_complex_3seeds.csv,complex,0,NaN,...,NaN,"[""hat"", ""top"", ""coat"", ""rack""]",0,NaN,NaN,NaN,NaN,NaN,0.0,NaN
2,complex_000000,complex,The red hat was on top of the brown coat rack.,flux,2,/content/drive/MyDrive/Vision_Language_Models_...,generated_index_flux_complex_3seeds.csv,complex,0,NaN,...,NaN,"[""hat"", ""top"", ""coat"", ""rack""]",0,NaN,NaN,NaN,NaN,NaN,0.0,NaN
3,complex_000001,complex,The blue water bottle was on top of the red ba...,flux,0,/content/drive/MyDrive/Vision_Language_Models_...,generated_index_flux_complex_3seeds.csv,complex,0,NaN,...,NaN,"[""water"", ""bottle"", ""top"", ""backpack""]",0,NaN,NaN,NaN,NaN,NaN,0.0,NaN
4,complex_000001,complex,The blue water bottle was on top of the red ba...,flux,1,/content/drive/MyDrive/Vision_Language_Models_...,generated_index_flux_complex_3seeds.csv,complex,0,NaN,...,NaN,"[""water"", ""bottle"", ""top"", ""backpack""]",0,NaN,NaN,NaN,NaN,NaN,0.0,NaN

## 5. Creating a Pilot Subset

Before evaluating the full dataset, a smaller pilot subset is created.

This pilot set is useful for:
- verifying that model loading works,
- checking JSON output formatting,
- testing prompt variants,
- and confirming that the VLM judges behave sensibly before scaling up to all images.

In [ ]:
# take a small pilot: 30 per split-model combination
pilot_df = (
    eval_df.groupby(["split", "gen_model"], group_keys=False)
    .head(30)
    .reset_index(drop=True)
)

print("pilot rows:", len(pilot_df))
pilot_df["split"].value_counts()

pilot rows: 240

split
complex       60
3d_spatial    60
numeracy      60
spatial       60
Name: count, dtype: int64

## 6. Choosing the Evaluation Subset

At first, the pilot subset is used for debugging and validation.  
Later, this can be replaced with the full evaluation dataframe to run VLM judging on all generated images.

In [ ]:
judge_df = eval_df.copy()
print("judge rows:", len(judge_df))

judge rows: 7200

## 7. Prompt Variants for VLM-as-a-Judge

The VLM judges are tested with multiple prompt variants.

All variants follow the same high-level goal:
- judge whether the required objects are present,
- judge whether the intended relation, count, or composition is correct,
- and return structured scores in JSON format.

The prompt variants differ only in how explicitly the scoring rubric is described to the model.

### Prompt Variant 1
The first variant is a **short and simple judge instruction**.  
It tells the VLM to act as a strict visual evaluator, to judge only from the image and the original prompt, and to return valid JSON. This version is useful as a lightweight baseline because it gives the model relatively little extra guidance.

### Prompt Variant 2
The second variant is a **more explicit rubric-based instruction**.  
It not only asks for JSON output, but also defines the meaning of each score from **1 to 5** for:
- `presence_score`, and
- `relation_score`.

This version is expected to produce more stable and consistent judgments because the scoring criteria are spelled out more clearly.

Testing multiple variants helps determine which instruction style produces the most reliable VLM-as-a-Judge behavior.

In [ ]:
PROMPT_VARIANTS = {
    "prompt_v1": {
        "system": (
            "You are a strict visual evaluator for generated images. "
            "Judge only from the image and the original text prompt. "
            "Do not rely on assumptions beyond what is visible. "
            "Return only valid JSON with no markdown."
        )
    },
    "prompt_v2": {
        "system": (
            "You are a strict multimodal judge for image-prompt alignment. "
            "Judge only from the given image and the original text prompt. "
            "Return only valid JSON with no markdown. "
            "Use this rubric exactly: "
            "presence_score: 1=most required objects missing, "
            "2=several required objects missing or unclear, "
            "3=main objects present but at least one important object unclear or missing, "
            "4=all key objects present with small ambiguity, "
            "5=all required objects clearly present. "
            "relation_score: 1=relation/count/layout clearly wrong, "
            "2=mostly wrong, "
            "3=ambiguous or partially correct, "
            "4=mostly correct with small issues, "
            "5=clearly correct."
        )
    }
}

## 8. Building Split-Specific Judge Instructions

The benchmark contains multiple task types:
- 2D spatial,
- 3D spatial,
- numeracy,
- and complex composition.

Because these tasks require different types of reasoning, the judge instruction is adapted to the split.

Importantly, the VLM judge is given only:
- the generated image,
- and the original prompt.

It is intentionally kept independent from the automatic extraction pipeline so that its outputs can later be compared fairly against the proxy labels from Notebook 2.

In [ ]:
def build_judge_instruction(row, variant_name="prompt_v1"):
    split = row["split"]
    prompt = row["text"]

    if split in ["spatial", "3d_spatial"]:
        return f"""
Evaluate the image against this original prompt:

PROMPT: "{prompt}"

Return only valid JSON with exactly these keys:
{{
  "presence_score": 1-5,
  "relation_score": 1-5,
  "reason": "short reason"
}}

Scoring meaning:
- presence_score: how well the objects required by the prompt are present in the image
- relation_score: how well the spatial relationship in the prompt is satisfied

For 3D spatial prompts such as "in front of", "behind", or "hidden by",
judge only from visible evidence in the image such as occlusion and relative placement.
Do not use outside world knowledge.
""".strip()

    elif split == "numeracy":
        return f"""
Evaluate the image against this original prompt:

PROMPT: "{prompt}"

Return only valid JSON with exactly these keys:
{{
  "presence_score": 1-5,
  "relation_score": 1-5,
  "reason": "short reason"
}}

Scoring meaning:
- presence_score: how well the required object categories mentioned in the prompt are present
- relation_score: how correct the object counts are

Judge only from what is visible in the image.
""".strip()

    else:
        return f"""
Evaluate the image against this original prompt:

PROMPT: "{prompt}"

Return only valid JSON with exactly these keys:
{{
  "presence_score": 1-5,
  "relation_score": 1-5,
  "reason": "short reason"
}}

Scoring meaning:
- presence_score: how well the important objects described in the prompt are present
- relation_score: how well the overall arrangement, relations, and composition match the prompt

Judge only from the image and the original prompt.
Do not rely on extracted helper fields or assumptions.
""".strip()

## 9. Selecting the Judge Model and Prompt Variant

This section selects:
- which VLM judge will be used in the current run,
- and which prompt variant will be used to instruct the judge.

Only one judge model is loaded at a time in order to reduce GPU memory usage and simplify long evaluation runs.

## Judge Run — Qwen2.5-VL with Prompt Variant 1

This section runs the VLM-as-a-Judge pipeline using:

- **Judge model**: Qwen2.5-VL  
- **Prompt variant**: Prompt Variant 1

In this configuration, the judge receives the generated image and the original text prompt, and produces structured JSON scores for:
- object presence,
- and relation/count/composition correctness.

This run is used to evaluate how Qwen2.5-VL behaves under the simpler instruction setting.

In [ ]:
# "qwen25_vl_7b", "qwen3_vl_4b", "gemma3_4b"
JUDGE_MODEL_KEY = "qwen25_vl_7b"

# choose prompt variant
PROMPT_VARIANT = "prompt_v1"

## 10. Hugging Face Authentication

Some VLM checkpoints require authentication before they can be downloaded from Hugging Face.

This section logs into the Hugging Face Hub so that the selected judge model can be loaded.

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

In [ ]:
from huggingface_hub import notebook_login
notebook_login()

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

## 11. Loading the VLM Judge

This section loads the selected multimodal judge model and its processor.

Each supported model is loaded through a unified helper function so that the rest of the notebook can use the same inference pipeline regardless of whether the judge is:
- Qwen2.5-VL,
- Qwen3-VL,
- or Gemma 3.

In [ ]:
clear_vram()

from transformers import AutoProcessor

def load_vlm(model_key):
    model_key = model_key.lower().strip()

    if model_key == "qwen25_vl_7b":
        from transformers import Qwen2_5_VLForConditionalGeneration
        model_id = "Qwen/Qwen2.5-VL-7B-Instruct"
        model = Qwen2_5_VLForConditionalGeneration.from_pretrained(
            model_id,
            dtype=DTYPE,
            device_map="auto",
            attn_implementation="sdpa"
        )
        processor = AutoProcessor.from_pretrained(model_id)
        return model, processor, model_id

    if model_key == "qwen3_vl_4b":
        from transformers import Qwen3VLForConditionalGeneration
        model_id = "Qwen/Qwen3-VL-4B-Instruct"
        model = Qwen3VLForConditionalGeneration.from_pretrained(
            model_id,
            dtype=DTYPE,
            device_map="auto",
            attn_implementation="sdpa"
        )
        processor = AutoProcessor.from_pretrained(model_id)
        return model, processor, model_id

    if model_key == "gemma3_4b":
        from transformers import Gemma3ForConditionalGeneration
        model_id = "google/gemma-3-4b-it"
        model = Gemma3ForConditionalGeneration.from_pretrained(
            model_id,
            dtype=DTYPE,
            device_map="auto"
        )
        processor = AutoProcessor.from_pretrained(model_id, padding_side="left")
        return model, processor, model_id

    raise ValueError("Unknown model_key")

model, processor, model_id = load_vlm(JUDGE_MODEL_KEY)
print("Loaded:", model_id)

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 5 files:   0%|          | 0/5 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/729 [00:00<?, ?it/s]

The image processor of type `Qwen2VLImageProcessor` is now loaded as a fast processor by default, even if the model checkpoint was saved with a slow processor. This is a breaking change and may produce slightly different outputs. To continue using the slow processor, instantiate this class with `use_fast=False`.

Loaded: Qwen/Qwen2.5-VL-7B-Instruct

## 12. Building Multimodal Inputs and Generating Judge Outputs

This section constructs the multimodal input given to the judge:
- the generated image,
- the system instruction,
- and the user prompt.

The judge is asked to return a JSON object containing:
- `presence_score`,
- `relation_score`,
- and a short textual reason.

Generation is performed deterministically so that the same image and prompt yield consistent outputs.

In [ ]:
def build_messages(image_path, instruction, system_text):
    image = Image.open(image_path).convert("RGB")
    messages = [
        {
            "role": "system",
            "content": [{"type": "text", "text": system_text}]
        },
        {
            "role": "user",
            "content": [
                {"type": "image", "image": image},
                {"type": "text", "text": instruction}
            ]
        }
    ]
    return messages

def generate_vlm_json(image_path, instruction, system_text, max_new_tokens=220):
    messages = build_messages(image_path, instruction, system_text)

    inputs = processor.apply_chat_template(
        messages,
        tokenize=True,
        add_generation_prompt=True,
        return_dict=True,
        return_tensors="pt"
    )

    inputs.pop("token_type_ids", None)

    # move tensors
    for k, v in inputs.items():
        if torch.is_tensor(v):
            inputs[k] = v.to(model.device)

    with torch.inference_mode():
        output_ids = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False
        )

    # decode only newly generated tokens
    new_tokens = output_ids[:, inputs["input_ids"].shape[1]:]
    text = processor.batch_decode(
        new_tokens,
        skip_special_tokens=True,
        clean_up_tokenization_spaces=False
    )[0]

    return text.strip()

## 13. Parsing the Judge Response

Because VLM outputs are generated as text, this section extracts the JSON block from the raw model response and converts it into structured fields.

The parsing step records:
- the judge scores,
- the short explanation,
- whether JSON parsing succeeded,
- and the raw text output for debugging.

This makes the evaluation pipeline more robust when models occasionally produce imperfect formatting.

In [ ]:
def extract_json_block(text):
    # find first {...} block
    m = re.search(r"\{.*\}", text, flags=re.DOTALL)
    if m:
        return m.group(0)
    return None

def parse_judge_output(raw_text):
    block = extract_json_block(raw_text)
    if block is None:
        return {
            "presence_score": None,
            "relation_score": None,
            "reason": raw_text[:500],
            "parse_ok": 0,
            "raw_output": raw_text
        }

    try:
        obj = json.loads(block)
        return {
            "presence_score": int(obj.get("presence_score")) if obj.get("presence_score") is not None else None,
            "relation_score": int(obj.get("relation_score")) if obj.get("relation_score") is not None else None,
            "reason": str(obj.get("reason", "")),
            "parse_ok": 1,
            "raw_output": raw_text
        }
    except Exception:
        return {
            "presence_score": None,
            "relation_score": None,
            "reason": raw_text[:500],
            "parse_ok": 0,
            "raw_output": raw_text
        }

## 14. Defining the Output File

For each VLM judge and prompt variant, the results are stored in a separate CSV file.

This makes it easy to compare:
- different VLM judges,
- different prompt variants,
- and repeated runs across the same dataset.

In [ ]:
safe_model = JUDGE_MODEL_KEY
safe_prompt = PROMPT_VARIANT

VLM_OUT = os.path.join(
    DIR_TABLES,
    f"vlm_judge_{safe_model}_{safe_prompt}.csv"
)

print(VLM_OUT)

/content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v1.csv

## 15. Main VLM-as-a-Judge Evaluation Loop

This section applies the selected VLM judge to the chosen dataset subset.

For each image, the notebook:
1. builds the multimodal input,
2. runs the judge model,
3. parses the returned JSON,
4. stores the scores and explanation,
5. and saves the results incrementally to disk.

The loop is resume-safe, so interrupted runs can continue from previously saved outputs.

In [ ]:
def run_vlm_judge(df, out_csv, model_key, prompt_variant, save_every=25):
    done = set()
    rows = []

    if os.path.exists(out_csv):
        prev = pd.read_csv(out_csv)
        rows = prev.to_dict("records")
        done = set(zip(prev["prompt_id"], prev["gen_model"], prev["seed"]))
        print(f"[RESUME] loaded {len(prev)} previous rows")

    system_text = PROMPT_VARIANTS[prompt_variant]["system"]

    new = 0
    for _, r in df.iterrows():
        key = (r["prompt_id"], r["gen_model"], int(r["seed"]))
        if key in done:
            continue

        instruction = build_judge_instruction(r, variant_name=prompt_variant)

        raw_text = generate_vlm_json(
            image_path=r["image_path"],
            instruction=instruction,
            system_text=system_text,
            max_new_tokens=220
        )

        parsed = parse_judge_output(raw_text)

        rec = {
            "prompt_id": r["prompt_id"],
            "split": r["split"],
            "gen_model": r["gen_model"],
            "seed": int(r["seed"]),
            "image_path": r["image_path"],
            "text": r["text"],
            "judge_model": model_key,
            "prompt_variant": prompt_variant,
            "presence_score": parsed["presence_score"],
            "relation_score": parsed["relation_score"],
            "reason": parsed["reason"],
            "parse_ok": parsed["parse_ok"],
            "raw_output": parsed["raw_output"],
            "gt_presence_proxy": r.get("gt_presence_proxy", np.nan),
            "gt_relation_proxy": r.get("gt_relation_proxy", np.nan),
        }

        rows.append(rec)
        done.add(key)
        new += 1

        if new % save_every == 0:
            pd.DataFrame(rows).to_csv(out_csv, index=False)
            print(f"[CHK] saved {len(rows)} rows -> {out_csv}")

    out_df = pd.DataFrame(rows)
    out_df.to_csv(out_csv, index=False)
    print("Saved:", out_csv, "rows:", len(out_df))
    return out_df

## 16. Running the Judge on the Selected Dataset

This cell launches the evaluation for the selected VLM judge and prompt variant.

At first, the pilot subset can be used to validate output quality.  
Later, the same pipeline can be run on the full dataset.

In [ ]:


judge_results_df = run_vlm_judge(
    df=judge_df,
    out_csv=VLM_OUT,
    model_key=JUDGE_MODEL_KEY,
    prompt_variant=PROMPT_VARIANT,
    save_every=25
)

judge_results_df.head()

[RESUME] loaded 7200 previous rows
Saved: /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v1.csv rows: 7200

,prompt_id,split,gen_model,seed,image_path,text,judge_model,prompt_variant,presence_score,relation_score,reason,parse_ok,raw_output,gt_presence_proxy,gt_relation_proxy
0,complex_000000,complex,flux,0,/content/drive/MyDrive/Vision_Language_Models_...,The red hat was on top of the brown coat rack.,qwen25_vl_7b,prompt_v1,4,3,The red hat is present but not on a coat rack;...,1,"{\n ""presence_score"": 4,\n ""relation_score"":...",0.0,NaN
1,complex_000000,complex,flux,1,/content/drive/MyDrive/Vision_Language_Models_...,The red hat was on top of the brown coat rack.,qwen25_vl_7b,prompt_v1,4,3,The red hat is present but not on top of the b...,1,"{\n ""presence_score"": 4,\n ""relation_score"":...",0.0,NaN
2,complex_000000,complex,flux,2,/content/drive/MyDrive/Vision_Language_Models_...,The red hat was on top of the brown coat rack.,qwen25_vl_7b,prompt_v1,2,1,The red hat is present but not on a coat rack;...,1,"{\n ""presence_score"": 2,\n ""relation_score"":...",0.0,NaN
3,complex_000001,complex,flux,0,/content/drive/MyDrive/Vision_Language_Models_...,The blue water bottle was on top of the red ba...,qwen25_vl_7b,prompt_v1,5,5,The blue water bottle is clearly placed on top...,1,"{\n ""presence_score"": 5,\n ""relation_score"":...",0.0,NaN
4,complex_000001,complex,flux,1,/content/drive/MyDrive/Vision_Language_Models_...,The blue water bottle was on top of the red ba...,qwen25_vl_7b,prompt_v1,4,4,The blue water bottle is clearly on top of the...,1,"{\n ""presence_score"": 4,\n ""relation_score"":...",0.0,NaN

## 17. Judge Score Summary

After inference, the mean presence and relation scores are summarized by split and generator model.

This provides an initial view of how the VLM judge evaluates the generated images across the different benchmark categories.

In [ ]:
judge_results_df.groupby(["split", "gen_model"])[["presence_score", "relation_score"]].mean()

                      presence_score  relation_score
split      gen_model
3d_spatial flux             3.191111        2.792222
           sdxl             3.086667        2.682222
complex    flux             3.885556        3.316667
           sdxl             3.487778        2.803333
numeracy   flux             3.494444        3.006667
           sdxl             2.731111        2.183333
spatial    flux             3.826667        3.406667
           sdxl             3.733333        3.062222

## 18. Binary Agreement with Proxy Labels

To compare judge outputs with the automatic proxy labels, the 1–5 judge scores are converted into binary decisions.

This enables a simple agreement analysis between:
- the VLM judge,
- and the extraction-based proxy pipeline from Notebook 2.

In [ ]:
# binary conversion for the judge
judge_results_df["presence_bin"] = judge_results_df["presence_score"].apply(
    lambda x: 1 if pd.notna(x) and x >= 4 else (0 if pd.notna(x) and x <= 2 else np.nan)
)
judge_results_df["relation_bin"] = judge_results_df["relation_score"].apply(
    lambda x: 1 if pd.notna(x) and x >= 4 else (0 if pd.notna(x) and x <= 2 else np.nan)
)

# relation proxy bin
def relation_proxy_bin(row):
    split = row["split"]
    gt = row["gt_relation_proxy"]
    if pd.isna(gt):
        return np.nan
    if split == "numeracy":
        # exact-positive only
        return 1 if gt >= 0.999 else 0
    return int(gt >= 0.5)

judge_results_df["gt_relation_bin"] = judge_results_df.apply(relation_proxy_bin, axis=1)

def binary_accuracy(sub, pred_col, gt_col):
    sub = sub[[pred_col, gt_col]].dropna()
    if len(sub) == 0:
        return np.nan
    return (sub[pred_col] == sub[gt_col]).mean()

binary_summary = []
for (split, gen_model), sub in judge_results_df.groupby(["split", "gen_model"]):
    binary_summary.append({
        "split": split,
        "gen_model": gen_model,
        "relation_bin_acc": binary_accuracy(sub, "relation_bin", "gt_relation_bin")
    })

binary_summary_df = pd.DataFrame(binary_summary)
binary_summary_df

        split gen_model  relation_bin_acc
0  3d_spatial      flux          0.204969
1  3d_spatial      sdxl          0.255814
2     complex      flux          0.818182
3     complex      sdxl          0.272727
4    numeracy      flux          0.605263
5    numeracy      sdxl          0.842988
6     spatial      flux          0.608025
7     spatial      sdxl          0.574176

## 19. Correlation with Proxy Scores

In addition to binary agreement, this section measures how strongly the VLM judge scores correlate with the automatic proxy scores.

This provides a more fine-grained comparison than thresholded binary labels and helps evaluate whether higher VLM scores are associated with better proxy-ground-truth alignment.

In [ ]:
corr_rows = []
for (split, gen_model), sub in judge_results_df.groupby(["split", "gen_model"]):
    sub = sub[["relation_score", "gt_relation_proxy"]].dropna()
    if len(sub) >= 3:
        rho, p = spearmanr(sub["relation_score"], sub["gt_relation_proxy"])
    else:
        rho, p = np.nan, np.nan
    corr_rows.append({
        "split": split,
        "gen_model": gen_model,
        "spearman_relation_vs_proxy": rho,
        "p_value": p,
        "n": len(sub)
    })

corr_df = pd.DataFrame(corr_rows)
corr_df

        split gen_model  spearman_relation_vs_proxy       p_value    n
0  3d_spatial      flux                   -0.543041  4.334627e-27  335
1  3d_spatial      sdxl                   -0.438156  1.197972e-18  367
2     complex      flux                   -0.058026  7.829261e-01   25
3     complex      sdxl                    0.356042  1.131705e-01   21
4    numeracy      flux                    0.126396  1.436175e-04  900
5    numeracy      sdxl                    0.136657  3.899888e-05  900
6     spatial      flux                    0.072315  1.900623e-01  330
7     spatial      sdxl                    0.109909  3.288945e-02  377

## Additional Judge Run — Qwen2.5-VL with Prompt Variant 2

This section runs the VLM-as-a-Judge pipeline using:

- **Judge model**: Qwen2.5-VL  
- **Prompt variant**: Prompt Variant 2

Compared with Prompt Variant 1, this version uses a more explicit rubric for the 1–5 scoring scale.  
This allows us to test whether a more detailed instruction leads to more stable or more interpretable judge outputs.

In [ ]:
# "qwen25_vl_7b", "qwen3_vl_4b", "gemma3_4b"
JUDGE_MODEL_KEY = "qwen25_vl_7b"

# choose prompt variant
PROMPT_VARIANT = "prompt_v2"

In [ ]:
safe_model = JUDGE_MODEL_KEY
safe_prompt = PROMPT_VARIANT

VLM_OUT = os.path.join(
    DIR_TABLES,
    f"vlm_judge_{safe_model}_{safe_prompt}.csv"
)

print(VLM_OUT)

/content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv

In [ ]:
judge_results_df = run_vlm_judge(
    df=judge_df,
    out_csv=VLM_OUT,
    model_key=JUDGE_MODEL_KEY,
    prompt_variant=PROMPT_VARIANT,
    save_every=25
)

judge_results_df.head()

[RESUME] loaded 5175 previous rows

The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[CHK] saved 5200 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 5225 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 5250 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 5275 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 5300 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 5325 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 5350 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 5375 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 5400 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 5425 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 5450 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 5475 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 5500 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 5525 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 5550 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 5575 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 5600 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 5625 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 5650 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 5675 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 5700 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 5725 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 5750 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 5775 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 5800 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 5825 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 5850 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 5875 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 5900 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 5925 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 5950 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 5975 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 6000 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 6025 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 6050 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 6075 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 6100 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 6125 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 6150 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 6175 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 6200 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 6225 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 6250 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 6275 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 6300 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 6325 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 6350 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 6375 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 6400 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 6425 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 6450 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 6475 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 6500 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 6525 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 6550 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 6575 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 6600 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 6625 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 6650 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 6675 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 6700 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 6725 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 6750 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 6775 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 6800 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 6825 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 6850 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 6875 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 6900 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 6925 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 6950 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 6975 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 7000 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 7025 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 7050 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 7075 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 7100 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 7125 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 7150 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 7175 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
[CHK] saved 7200 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv
Saved: /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen25_vl_7b_prompt_v2.csv rows: 7200

,prompt_id,split,gen_model,seed,image_path,text,judge_model,prompt_variant,presence_score,relation_score,reason,parse_ok,raw_output,gt_presence_proxy,gt_relation_proxy
0,complex_000000,complex,flux,0,/content/drive/MyDrive/Vision_Language_Models_...,The red hat was on top of the brown coat rack.,qwen25_vl_7b,prompt_v2,3,3,"The red hat is present, but the brown coat is ...",1,"{\n ""presence_score"": 3,\n ""relation_score"":...",0.0,NaN
1,complex_000000,complex,flux,1,/content/drive/MyDrive/Vision_Language_Models_...,The red hat was on top of the brown coat rack.,qwen25_vl_7b,prompt_v2,4,4,The red hat is clearly visible and appears to ...,1,"{\n ""presence_score"": 4,\n ""relation_score"":...",0.0,NaN
2,complex_000000,complex,flux,2,/content/drive/MyDrive/Vision_Language_Models_...,The red hat was on top of the brown coat rack.,qwen25_vl_7b,prompt_v2,1,1,"The image shows a red hat and a brown coat, bu...",1,"{\n ""presence_score"": 1,\n ""relation_score"":...",0.0,NaN
3,complex_000001,complex,flux,0,/content/drive/MyDrive/Vision_Language_Models_...,The blue water bottle was on top of the red ba...,qwen25_vl_7b,prompt_v2,5,5,Both the blue water bottle and the red backpac...,1,"{\n ""presence_score"": 5,\n ""relation_score"":...",0.0,NaN
4,complex_000001,complex,flux,1,/content/drive/MyDrive/Vision_Language_Models_...,The blue water bottle was on top of the red ba...,qwen25_vl_7b,prompt_v2,5,5,Both the blue water bottle and the red backpac...,1,"{\n ""presence_score"": 5,\n ""relation_score"":...",0.0,NaN

In [ ]:
judge_results_df.groupby(["split", "gen_model"])[["presence_score", "relation_score"]].mean()

                      presence_score  relation_score
split      gen_model
3d_spatial flux             3.387778        3.377778
           sdxl             3.574444        3.500000
complex    flux             4.188889        4.093333
           sdxl             3.828889        3.606667
numeracy   flux             3.746667        3.634444
           sdxl             3.151111        3.013333
spatial    flux             4.125556        4.054444
           sdxl             4.012222        3.971111

In [ ]:
# binary conversion for the judge
judge_results_df["presence_bin"] = judge_results_df["presence_score"].apply(
    lambda x: 1 if pd.notna(x) and x >= 4 else (0 if pd.notna(x) and x <= 2 else np.nan)
)
judge_results_df["relation_bin"] = judge_results_df["relation_score"].apply(
    lambda x: 1 if pd.notna(x) and x >= 4 else (0 if pd.notna(x) and x <= 2 else np.nan)
)

# relation proxy bin
def relation_proxy_bin(row):
    split = row["split"]
    gt = row["gt_relation_proxy"]
    if pd.isna(gt):
        return np.nan
    if split == "numeracy":
        # exact-positive only
        return 1 if gt >= 0.999 else 0
    return int(gt >= 0.5)

judge_results_df["gt_relation_bin"] = judge_results_df.apply(relation_proxy_bin, axis=1)

def binary_accuracy(sub, pred_col, gt_col):
    sub = sub[[pred_col, gt_col]].dropna()
    if len(sub) == 0:
        return np.nan
    return (sub[pred_col] == sub[gt_col]).mean()

binary_summary = []
for (split, gen_model), sub in judge_results_df.groupby(["split", "gen_model"]):
    binary_summary.append({
        "split": split,
        "gen_model": gen_model,
        "relation_bin_acc": binary_accuracy(sub, "relation_bin", "gt_relation_bin")
    })

binary_summary_df = pd.DataFrame(binary_summary)
binary_summary_df

        split gen_model  relation_bin_acc
0  3d_spatial      flux          0.123552
1  3d_spatial      sdxl          0.242321
2     complex      flux          0.863636
3     complex      sdxl          0.631579
4    numeracy      flux          0.328340
5    numeracy      sdxl          0.479167
6     spatial      flux          0.625442
7     spatial      sdxl          0.610922

In [ ]:
corr_rows = []
for (split, gen_model), sub in judge_results_df.groupby(["split", "gen_model"]):
    sub = sub[["relation_score", "gt_relation_proxy"]].dropna()
    if len(sub) >= 3:
        rho, p = spearmanr(sub["relation_score"], sub["gt_relation_proxy"])
    else:
        rho, p = np.nan, np.nan
    corr_rows.append({
        "split": split,
        "gen_model": gen_model,
        "spearman_relation_vs_proxy": rho,
        "p_value": p,
        "n": len(sub)
    })

corr_df = pd.DataFrame(corr_rows)
corr_df

        split gen_model  spearman_relation_vs_proxy       p_value    n
0  3d_spatial      flux                   -0.642706  1.995210e-40  335
1  3d_spatial      sdxl                   -0.471971  9.316418e-22  367
2     complex      flux                   -0.078242  7.100770e-01   25
3     complex      sdxl                    0.347524  1.226829e-01   21
4    numeracy      flux                    0.169553  3.110668e-07  900
5    numeracy      sdxl                    0.145602  1.157780e-05  900
6     spatial      flux                    0.041541  4.519998e-01  330
7     spatial      sdxl                    0.042173  4.142171e-01  377

## Additional Judge Run — Qwen3-VL with Prompt Variant 1

This section runs the VLM-as-a-Judge pipeline using:

- **Judge model**: Qwen3-VL  
- **Prompt variant**: Prompt Variant 1

This experiment allows us to compare the behavior of Qwen3-VL against the other judge models under the simpler instruction setting.

In [ ]:
# "qwen25_vl_7b", "qwen3_vl_4b", "gemma3_4b"
JUDGE_MODEL_KEY = "qwen3_vl_4b"

# choose prompt variant
PROMPT_VARIANT = "prompt_v1"

In [ ]:
safe_model = JUDGE_MODEL_KEY
safe_prompt = PROMPT_VARIANT

VLM_OUT = os.path.join(
    DIR_TABLES,
    f"vlm_judge_{safe_model}_{safe_prompt}.csv"
)

print(VLM_OUT)

/content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv

In [ ]:
clear_vram()

from transformers import AutoProcessor

def load_vlm(model_key):
    model_key = model_key.lower().strip()

    if model_key == "qwen25_vl_7b":
        from transformers import Qwen2_5_VLForConditionalGeneration
        model_id = "Qwen/Qwen2.5-VL-7B-Instruct"
        model = Qwen2_5_VLForConditionalGeneration.from_pretrained(
            model_id,
            dtype=DTYPE,
            device_map="auto",
            attn_implementation="sdpa"
        )
        processor = AutoProcessor.from_pretrained(model_id)
        return model, processor, model_id

    if model_key == "qwen3_vl_4b":
        from transformers import Qwen3VLForConditionalGeneration
        model_id = "Qwen/Qwen3-VL-4B-Instruct"
        model = Qwen3VLForConditionalGeneration.from_pretrained(
            model_id,
            dtype=DTYPE,
            device_map="auto",
            attn_implementation="sdpa"
        )
        processor = AutoProcessor.from_pretrained(model_id)
        return model, processor, model_id

    if model_key == "gemma3_4b":
        from transformers import Gemma3ForConditionalGeneration
        model_id = "google/gemma-3-4b-it"
        model = Gemma3ForConditionalGeneration.from_pretrained(
            model_id,
            dtype=DTYPE,
            device_map="auto"
        )
        processor = AutoProcessor.from_pretrained(model_id, padding_side="left")
        return model, processor, model_id

    raise ValueError("Unknown model_key")

In [ ]:
model, processor, model_id = load_vlm(JUDGE_MODEL_KEY)
print("Loaded:", model_id)

config.json: 0.00B [00:00, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/713 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/269 [00:00<?, ?B/s]

preprocessor_config.json:   0%|          | 0.00/390 [00:00<?, ?B/s]

chat_template.json: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

video_preprocessor_config.json:   0%|          | 0.00/385 [00:00<?, ?B/s]

Loaded: Qwen/Qwen3-VL-4B-Instruct

In [ ]:
judge_results_df = run_vlm_judge(
    df=judge_df,
    out_csv=VLM_OUT,
    model_key=JUDGE_MODEL_KEY,
    prompt_variant=PROMPT_VARIANT,
    save_every=25
)

judge_results_df.head()

[RESUME] loaded 4300 previous rows

The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[CHK] saved 4325 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 4350 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 4375 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 4400 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 4425 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 4450 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 4475 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 4500 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 4525 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 4550 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 4575 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 4600 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 4625 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 4650 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 4675 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 4700 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 4725 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 4750 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 4775 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 4800 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 4825 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 4850 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 4875 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 4900 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 4925 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 4950 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 4975 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 5000 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 5025 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 5050 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 5075 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 5100 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 5125 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 5150 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 5175 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 5200 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 5225 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 5250 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 5275 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 5300 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 5325 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 5350 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 5375 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 5400 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 5425 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 5450 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 5475 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 5500 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 5525 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 5550 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 5575 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 5600 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 5625 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 5650 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 5675 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 5700 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 5725 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 5750 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 5775 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 5800 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 5825 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 5850 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 5875 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 5900 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 5925 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 5950 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 5975 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 6000 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 6025 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 6050 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 6075 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 6100 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 6125 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 6150 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 6175 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 6200 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 6225 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 6250 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 6275 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 6300 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 6325 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 6350 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 6375 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 6400 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 6425 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 6450 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 6475 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 6500 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 6525 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 6550 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 6575 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 6600 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 6625 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 6650 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 6675 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 6700 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 6725 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 6750 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 6775 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 6800 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 6825 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 6850 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 6875 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 6900 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 6925 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 6950 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 6975 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 7000 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 7025 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 7050 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 7075 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 7100 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 7125 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 7150 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 7175 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
[CHK] saved 7200 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv
Saved: /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v1.csv rows: 7200

,prompt_id,split,gen_model,seed,image_path,text,judge_model,prompt_variant,presence_score,relation_score,reason,parse_ok,raw_output,gt_presence_proxy,gt_relation_proxy
0,complex_000000,complex,flux,0,/content/drive/MyDrive/Vision_Language_Models_...,The red hat was on top of the brown coat rack.,qwen3_vl_4b,prompt_v1,5.0,2.0,"The red hat and brown coat are present, but th...",1,"{\n ""presence_score"": 5,\n ""relation_score"":...",0.0,NaN
1,complex_000000,complex,flux,1,/content/drive/MyDrive/Vision_Language_Models_...,The red hat was on top of the brown coat rack.,qwen3_vl_4b,prompt_v1,5.0,2.0,The red hat is present but not on a coat rack;...,1,"{\n ""presence_score"": 5,\n ""relation_score"":...",0.0,NaN
2,complex_000000,complex,flux,2,/content/drive/MyDrive/Vision_Language_Models_...,The red hat was on top of the brown coat rack.,qwen3_vl_4b,prompt_v1,5.0,1.0,The hat is not on a coat rack; it is worn by a...,1,"{\n ""presence_score"": 5,\n ""relation_score"":...",0.0,NaN
3,complex_000001,complex,flux,0,/content/drive/MyDrive/Vision_Language_Models_...,The blue water bottle was on top of the red ba...,qwen3_vl_4b,prompt_v1,5.0,5.0,The blue water bottle is clearly placed on top...,1,"{\n ""presence_score"": 5,\n ""relation_score"":...",0.0,NaN
4,complex_000001,complex,flux,1,/content/drive/MyDrive/Vision_Language_Models_...,The blue water bottle was on top of the red ba...,qwen3_vl_4b,prompt_v1,5.0,2.0,The blue water bottle is inside the red backpa...,1,"{\n ""presence_score"": 5,\n ""relation_score"":...",0.0,NaN

In [ ]:
judge_results_df.groupby(["split", "gen_model"])[["presence_score", "relation_score"]].mean()

                      presence_score  relation_score
split      gen_model
3d_spatial flux             4.760845        3.859844
           sdxl             4.600000        3.792222
complex    flux             4.820000        4.477778
           sdxl             4.477778        3.774444
numeracy   flux             4.076667        3.521111
           sdxl             3.422692        2.670745
spatial    flux             4.763333        4.558889
           sdxl             4.736667        4.464444

In [ ]:
# binary conversion for the judge
judge_results_df["presence_bin"] = judge_results_df["presence_score"].apply(
    lambda x: 1 if pd.notna(x) and x >= 4 else (0 if pd.notna(x) and x <= 2 else np.nan)
)
judge_results_df["relation_bin"] = judge_results_df["relation_score"].apply(
    lambda x: 1 if pd.notna(x) and x >= 4 else (0 if pd.notna(x) and x <= 2 else np.nan)
)

# relation proxy bin
def relation_proxy_bin(row):
    split = row["split"]
    gt = row["gt_relation_proxy"]
    if pd.isna(gt):
        return np.nan
    if split == "numeracy":
        # exact-positive only
        return 1 if gt >= 0.999 else 0
    return int(gt >= 0.5)

judge_results_df["gt_relation_bin"] = judge_results_df.apply(relation_proxy_bin, axis=1)

def binary_accuracy(sub, pred_col, gt_col):
    sub = sub[[pred_col, gt_col]].dropna()
    if len(sub) == 0:
        return np.nan
    return (sub[pred_col] == sub[gt_col]).mean()

binary_summary = []
for (split, gen_model), sub in judge_results_df.groupby(["split", "gen_model"]):
    binary_summary.append({
        "split": split,
        "gen_model": gen_model,
        "relation_bin_acc": binary_accuracy(sub, "relation_bin", "gt_relation_bin")
    })

binary_summary_df = pd.DataFrame(binary_summary)
binary_summary_df

        split gen_model  relation_bin_acc
0  3d_spatial      flux          0.225080
1  3d_spatial      sdxl          0.291545
2     complex      flux          0.920000
3     complex      sdxl          0.700000
4    numeracy      flux          0.437500
5    numeracy      sdxl          0.665100
6     spatial      flux          0.607903
7     spatial      sdxl          0.598383

In [ ]:
corr_rows = []
for (split, gen_model), sub in judge_results_df.groupby(["split", "gen_model"]):
    sub = sub[["relation_score", "gt_relation_proxy"]].dropna()
    if len(sub) >= 3:
        rho, p = spearmanr(sub["relation_score"], sub["gt_relation_proxy"])
    else:
        rho, p = np.nan, np.nan
    corr_rows.append({
        "split": split,
        "gen_model": gen_model,
        "spearman_relation_vs_proxy": rho,
        "p_value": p,
        "n": len(sub)
    })

corr_df = pd.DataFrame(corr_rows)
corr_df

        split gen_model  spearman_relation_vs_proxy       p_value    n
0  3d_spatial      flux                   -0.535506  2.961894e-26  335
1  3d_spatial      sdxl                   -0.281831  3.964554e-08  367
2     complex      flux                    0.272233  1.880044e-01   25
3     complex      sdxl                    0.498549  2.142699e-02   21
4    numeracy      flux                    0.190912  7.807323e-09  900
5    numeracy      sdxl                    0.187331  1.521057e-08  899
6     spatial      flux                   -0.050435  3.610814e-01  330
7     spatial      sdxl                    0.049662  3.362216e-01  377

## Additional Judge Run — Qwen3-VL with Prompt Variant 2

This section runs the VLM-as-a-Judge pipeline using:

- **Judge model**: Qwen3-VL  
- **Prompt variant**: Prompt Variant 2

This configuration tests whether Qwen3-VL benefits from a more explicit scoring rubric when judging image-prompt alignment.

In [ ]:
# "qwen25_vl_7b", "qwen3_vl_4b", "gemma3_4b"
JUDGE_MODEL_KEY = "qwen3_vl_4b"

# choose prompt variant
PROMPT_VARIANT = "prompt_v2"

In [ ]:
safe_model = JUDGE_MODEL_KEY
safe_prompt = PROMPT_VARIANT

VLM_OUT = os.path.join(
    DIR_TABLES,
    f"vlm_judge_{safe_model}_{safe_prompt}.csv"
)

print(VLM_OUT)

/content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv

In [ ]:
model, processor, model_id = load_vlm(JUDGE_MODEL_KEY)
print("Loaded:", model_id)

config.json: 0.00B [00:00, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/713 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/269 [00:00<?, ?B/s]

preprocessor_config.json:   0%|          | 0.00/390 [00:00<?, ?B/s]

chat_template.json: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

video_preprocessor_config.json:   0%|          | 0.00/385 [00:00<?, ?B/s]

Loaded: Qwen/Qwen3-VL-4B-Instruct

In [ ]:
judge_results_df = run_vlm_judge(
    df=judge_df,
    out_csv=VLM_OUT,
    model_key=JUDGE_MODEL_KEY,
    prompt_variant=PROMPT_VARIANT,
    save_every=25
)

judge_results_df.head()

[RESUME] loaded 5125 previous rows

The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[CHK] saved 5150 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 5175 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 5200 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 5225 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 5250 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 5275 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 5300 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 5325 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 5350 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 5375 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 5400 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 5425 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 5450 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 5475 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 5500 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 5525 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 5550 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 5575 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 5600 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 5625 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 5650 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 5675 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 5700 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 5725 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 5750 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 5775 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 5800 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 5825 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 5850 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 5875 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 5900 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 5925 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 5950 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 5975 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 6000 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 6025 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 6050 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 6075 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 6100 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 6125 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 6150 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 6175 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 6200 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 6225 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 6250 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 6275 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 6300 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 6325 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 6350 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 6375 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 6400 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 6425 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 6450 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 6475 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 6500 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 6525 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 6550 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 6575 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 6600 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 6625 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 6650 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 6675 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 6700 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 6725 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 6750 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 6775 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 6800 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 6825 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 6850 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 6875 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 6900 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 6925 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 6950 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 6975 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 7000 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 7025 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 7050 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 7075 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 7100 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 7125 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 7150 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 7175 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
[CHK] saved 7200 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv
Saved: /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_qwen3_vl_4b_prompt_v2.csv rows: 7200

,prompt_id,split,gen_model,seed,image_path,text,judge_model,prompt_variant,presence_score,relation_score,reason,parse_ok,raw_output,gt_presence_proxy,gt_relation_proxy
0,complex_000000,complex,flux,0,/content/drive/MyDrive/Vision_Language_Models_...,The red hat was on top of the brown coat rack.,qwen3_vl_4b,prompt_v2,3.0,2.0,"Red hat and brown coat are present, but the co...",1,"{\n ""presence_score"": 3,\n ""relation_score"":...",0.0,NaN
1,complex_000000,complex,flux,1,/content/drive/MyDrive/Vision_Language_Models_...,The red hat was on top of the brown coat rack.,qwen3_vl_4b,prompt_v2,3.0,2.0,Red hat is present but not on a coat rack; it'...,1,"{\n ""presence_score"": 3,\n ""relation_score"":...",0.0,NaN
2,complex_000000,complex,flux,2,/content/drive/MyDrive/Vision_Language_Models_...,The red hat was on top of the brown coat rack.,qwen3_vl_4b,prompt_v2,2.0,1.0,Hat and coat are present but not on a coat rac...,1,"{\n ""presence_score"": 2,\n ""relation_score"":...",0.0,NaN
3,complex_000001,complex,flux,0,/content/drive/MyDrive/Vision_Language_Models_...,The blue water bottle was on top of the red ba...,qwen3_vl_4b,prompt_v2,5.0,5.0,Blue water bottle and red backpack are clearly...,1,"{\n ""presence_score"": 5,\n ""relation_score"":...",0.0,NaN
4,complex_000001,complex,flux,1,/content/drive/MyDrive/Vision_Language_Models_...,The blue water bottle was on top of the red ba...,qwen3_vl_4b,prompt_v2,5.0,4.0,Blue water bottle and red backpack are clearly...,1,"{\n ""presence_score"": 5,\n ""relation_score"":...",0.0,NaN

In [ ]:
judge_results_df.groupby(["split", "gen_model"])[["presence_score", "relation_score"]].mean()

                      presence_score  relation_score
split      gen_model
3d_spatial flux             4.347052        4.133482
           sdxl             4.244444        3.998889
complex    flux             4.747778        4.637778
           sdxl             4.266667        4.045556
numeracy   flux             3.981111        3.644444
           sdxl             3.324444        2.906667
spatial    flux             4.612222        4.527778
           sdxl             4.598889        4.428889

In [ ]:
# binary conversion for the judge
judge_results_df["presence_bin"] = judge_results_df["presence_score"].apply(
    lambda x: 1 if pd.notna(x) and x >= 4 else (0 if pd.notna(x) and x <= 2 else np.nan)
)
judge_results_df["relation_bin"] = judge_results_df["relation_score"].apply(
    lambda x: 1 if pd.notna(x) and x >= 4 else (0 if pd.notna(x) and x <= 2 else np.nan)
)

# relation proxy bin
def relation_proxy_bin(row):
    split = row["split"]
    gt = row["gt_relation_proxy"]
    if pd.isna(gt):
        return np.nan
    if split == "numeracy":
        # exact-positive only
        return 1 if gt >= 0.999 else 0
    return int(gt >= 0.5)

judge_results_df["gt_relation_bin"] = judge_results_df.apply(relation_proxy_bin, axis=1)

def binary_accuracy(sub, pred_col, gt_col):
    sub = sub[[pred_col, gt_col]].dropna()
    if len(sub) == 0:
        return np.nan
    return (sub[pred_col] == sub[gt_col]).mean()

binary_summary = []
for (split, gen_model), sub in judge_results_df.groupby(["split", "gen_model"]):
    binary_summary.append({
        "split": split,
        "gen_model": gen_model,
        "relation_bin_acc": binary_accuracy(sub, "relation_bin", "gt_relation_bin")
    })

binary_summary_df = pd.DataFrame(binary_summary)
binary_summary_df

        split gen_model  relation_bin_acc
0  3d_spatial      flux          0.296073
1  3d_spatial      sdxl          0.323288
2     complex      flux          0.880000
3     complex      sdxl          0.714286
4    numeracy      flux          0.429561
5    numeracy      sdxl          0.625285
6     spatial      flux          0.606707
7     spatial      sdxl          0.603723

In [ ]:
corr_rows = []
for (split, gen_model), sub in judge_results_df.groupby(["split", "gen_model"]):
    sub = sub[["relation_score", "gt_relation_proxy"]].dropna()
    if len(sub) >= 3:
        rho, p = spearmanr(sub["relation_score"], sub["gt_relation_proxy"])
    else:
        rho, p = np.nan, np.nan
    corr_rows.append({
        "split": split,
        "gen_model": gen_model,
        "spearman_relation_vs_proxy": rho,
        "p_value": p,
        "n": len(sub)
    })

corr_df = pd.DataFrame(corr_rows)
corr_df

        split gen_model  spearman_relation_vs_proxy       p_value    n
0  3d_spatial      flux                   -0.377813  8.969471e-13  334
1  3d_spatial      sdxl                   -0.251011  1.113321e-06  367
2     complex      flux                   -0.075378  7.202655e-01   25
3     complex      sdxl                    0.326359  1.487759e-01   21
4    numeracy      flux                    0.197156  2.444767e-09  900
5    numeracy      sdxl                    0.155694  2.692718e-06  900
6     spatial      flux                   -0.022678  6.814757e-01  330
7     spatial      sdxl                    0.064512  2.113976e-01  377

## Additional Judge Run — Gemma 3 with Prompt Variant 1

This section runs the VLM-as-a-Judge pipeline using:

- **Judge model**: Gemma 3  
- **Prompt variant**: Prompt Variant 1

This run provides a judge output from a different VLM family, allowing cross-model comparison under the simpler prompt setting.

In [ ]:
# "qwen25_vl_7b", "qwen3_vl_4b", "gemma3_4b"
JUDGE_MODEL_KEY = "gemma3_4b"

# choose prompt variant
PROMPT_VARIANT = "prompt_v1"

In [ ]:
safe_model = JUDGE_MODEL_KEY
safe_prompt = PROMPT_VARIANT

VLM_OUT = os.path.join(
    DIR_TABLES,
    f"vlm_judge_{safe_model}_{safe_prompt}.csv"
)

print(VLM_OUT)

/content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v1.csv

In [ ]:
model, processor, model_id = load_vlm(JUDGE_MODEL_KEY)
print("Loaded:", model_id)

config.json:   0%|          | 0.00/855 [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/883 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/215 [00:00<?, ?B/s]

processor_config.json:   0%|          | 0.00/70.0 [00:00<?, ?B/s]

chat_template.json: 0.00B [00:00, ?B/s]

preprocessor_config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

The image processor of type `Gemma3ImageProcessor` is now loaded as a fast processor by default, even if the model checkpoint was saved with a slow processor. This is a breaking change and may produce slightly different outputs. To continue using the slow processor, instantiate this class with `use_fast=False`.

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/33.4M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/35.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/662 [00:00<?, ?B/s]

Loaded: google/gemma-3-4b-it

In [ ]:
judge_results_df = run_vlm_judge(
    df=judge_df,
    out_csv=VLM_OUT,
    model_key=JUDGE_MODEL_KEY,
    prompt_variant=PROMPT_VARIANT,
    save_every=25
)

judge_results_df.head()

[RESUME] loaded 5950 previous rows

The following generation flags are not valid and may be ignored: ['top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[CHK] saved 5975 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v1.csv
[CHK] saved 6000 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v1.csv
[CHK] saved 6025 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v1.csv
[CHK] saved 6050 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v1.csv
[CHK] saved 6075 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v1.csv
[CHK] saved 6100 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v1.csv
[CHK] saved 6125 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v1.csv
[CHK] saved 6150 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v1.csv
[CHK] saved 6175 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v1.csv
[CHK] saved 6200 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v1.csv
[CHK] saved 6225 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v1.csv
[CHK] saved 6250 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v1.csv
[CHK] saved 6275 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v1.csv
[CHK] saved 6300 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v1.csv
[CHK] saved 6325 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v1.csv
[CHK] saved 6350 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v1.csv
[CHK] saved 6375 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v1.csv
[CHK] saved 6400 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v1.csv
[CHK] saved 6425 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v1.csv
[CHK] saved 6450 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v1.csv
[CHK] saved 6475 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v1.csv
[CHK] saved 6500 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v1.csv
[CHK] saved 6525 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v1.csv
[CHK] saved 6550 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v1.csv
[CHK] saved 6575 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v1.csv
[CHK] saved 6600 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v1.csv
[CHK] saved 6625 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v1.csv
[CHK] saved 6650 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v1.csv
[CHK] saved 6675 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v1.csv
[CHK] saved 6700 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v1.csv
[CHK] saved 6725 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v1.csv
[CHK] saved 6750 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v1.csv
[CHK] saved 6775 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v1.csv
[CHK] saved 6800 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v1.csv
[CHK] saved 6825 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v1.csv
[CHK] saved 6850 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v1.csv
[CHK] saved 6875 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v1.csv
[CHK] saved 6900 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v1.csv
[CHK] saved 6925 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v1.csv
[CHK] saved 6950 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v1.csv
[CHK] saved 6975 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v1.csv
[CHK] saved 7000 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v1.csv
[CHK] saved 7025 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v1.csv
[CHK] saved 7050 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v1.csv
[CHK] saved 7075 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v1.csv
[CHK] saved 7100 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v1.csv
[CHK] saved 7125 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v1.csv
[CHK] saved 7150 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v1.csv
[CHK] saved 7175 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v1.csv
[CHK] saved 7200 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v1.csv
Saved: /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v1.csv rows: 7200

,prompt_id,split,gen_model,seed,image_path,text,judge_model,prompt_variant,presence_score,relation_score,reason,parse_ok,raw_output,gt_presence_proxy,gt_relation_proxy
0,complex_000000,complex,flux,0,/content/drive/MyDrive/Vision_Language_Models_...,The red hat was on top of the brown coat rack.,gemma3_4b,prompt_v1,5,4,The red hat is present and appears to be on to...,1,"```json\n{\n ""presence_score"": 5,\n ""relatio...",0.0,NaN
1,complex_000000,complex,flux,1,/content/drive/MyDrive/Vision_Language_Models_...,The red hat was on top of the brown coat rack.,gemma3_4b,prompt_v1,5,5,The red hat is clearly visible on top of the c...,1,"```json\n{\n ""presence_score"": 5,\n ""relatio...",0.0,NaN
2,complex_000000,complex,flux,2,/content/drive/MyDrive/Vision_Language_Models_...,The red hat was on top of the brown coat rack.,gemma3_4b,prompt_v1,5,4,The red hat is clearly visible on the person's...,1,"```json\n{\n ""presence_score"": 5,\n ""relatio...",0.0,NaN
3,complex_000001,complex,flux,0,/content/drive/MyDrive/Vision_Language_Models_...,The blue water bottle was on top of the red ba...,gemma3_4b,prompt_v1,5,5,The blue water bottle is on top of the red bac...,1,"```json\n{\n ""presence_score"": 5,\n ""relatio...",0.0,NaN
4,complex_000001,complex,flux,1,/content/drive/MyDrive/Vision_Language_Models_...,The blue water bottle was on top of the red ba...,gemma3_4b,prompt_v1,5,5,The blue water bottle is present on top of the...,1,"```json\n{\n ""presence_score"": 5,\n ""relatio...",0.0,NaN

In [ ]:
judge_results_df.groupby(["split", "gen_model"])[["presence_score", "relation_score"]].mean()

                      presence_score  relation_score
split      gen_model
3d_spatial flux             4.688889        4.848889
           sdxl             4.757778        4.870000
complex    flux             4.877778        4.843333
           sdxl             4.724444        4.688889
numeracy   flux             4.686667        4.606667
           sdxl             4.623333        4.526667
spatial    flux             4.768889        4.664444
           sdxl             4.842222        4.797778

In [ ]:
# binary conversion for the judge
judge_results_df["presence_bin"] = judge_results_df["presence_score"].apply(
    lambda x: 1 if pd.notna(x) and x >= 4 else (0 if pd.notna(x) and x <= 2 else np.nan)
)
judge_results_df["relation_bin"] = judge_results_df["relation_score"].apply(
    lambda x: 1 if pd.notna(x) and x >= 4 else (0 if pd.notna(x) and x <= 2 else np.nan)
)

# relation proxy bin
def relation_proxy_bin(row):
    split = row["split"]
    gt = row["gt_relation_proxy"]
    if pd.isna(gt):
        return np.nan
    if split == "numeracy":
        # exact-positive only
        return 1 if gt >= 0.999 else 0
    return int(gt >= 0.5)

judge_results_df["gt_relation_bin"] = judge_results_df.apply(relation_proxy_bin, axis=1)

def binary_accuracy(sub, pred_col, gt_col):
    sub = sub[[pred_col, gt_col]].dropna()
    if len(sub) == 0:
        return np.nan
    return (sub[pred_col] == sub[gt_col]).mean()

binary_summary = []
for (split, gen_model), sub in judge_results_df.groupby(["split", "gen_model"]):
    binary_summary.append({
        "split": split,
        "gen_model": gen_model,
        "relation_bin_acc": binary_accuracy(sub, "relation_bin", "gt_relation_bin")
    })

binary_summary_df = pd.DataFrame(binary_summary)
binary_summary_df

        split gen_model  relation_bin_acc
0  3d_spatial      flux          0.352239
1  3d_spatial      sdxl          0.355191
2     complex      flux          0.913043
3     complex      sdxl          0.850000
4    numeracy      flux          0.045397
5    numeracy      sdxl          0.054194
6     spatial      flux          0.620370
7     spatial      sdxl          0.595745

In [ ]:
corr_rows = []
for (split, gen_model), sub in judge_results_df.groupby(["split", "gen_model"]):
    sub = sub[["relation_score", "gt_relation_proxy"]].dropna()
    if len(sub) >= 3:
        rho, p = spearmanr(sub["relation_score"], sub["gt_relation_proxy"])
    else:
        rho, p = np.nan, np.nan
    corr_rows.append({
        "split": split,
        "gen_model": gen_model,
        "spearman_relation_vs_proxy": rho,
        "p_value": p,
        "n": len(sub)
    })

corr_df = pd.DataFrame(corr_rows)
corr_df

        split gen_model  spearman_relation_vs_proxy   p_value    n
0  3d_spatial      flux                   -0.225321  0.000032  335
1  3d_spatial      sdxl                   -0.140894  0.006863  367
2     complex      flux                    0.344828  0.091392   25
3     complex      sdxl                   -0.166227  0.471439   21
4    numeracy      flux                    0.135378  0.000046  900
5    numeracy      sdxl                    0.091713  0.005899  900
6     spatial      flux                   -0.018172  0.742248  330
7     spatial      sdxl                   -0.042387  0.411846  377

## Additional Judge Run — Gemma 3 with Prompt Variant 2

This section runs the VLM-as-a-Judge pipeline using:

- **Judge model**: Gemma 3  
- **Prompt variant**: Prompt Variant 2

This final configuration evaluates how Gemma 3 behaves when given the more explicit rubric-based judge prompt.

In [ ]:
# "qwen25_vl_7b", "qwen3_vl_4b", "gemma3_4b"
JUDGE_MODEL_KEY = "gemma3_4b"

# choose prompt variant
PROMPT_VARIANT = "prompt_v2"

In [ ]:
safe_model = JUDGE_MODEL_KEY
safe_prompt = PROMPT_VARIANT

VLM_OUT = os.path.join(
    DIR_TABLES,
    f"vlm_judge_{safe_model}_{safe_prompt}.csv"
)

print(VLM_OUT)

/content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv

In [ ]:
model, processor, model_id = load_vlm(JUDGE_MODEL_KEY)
print("Loaded:", model_id)

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/883 [00:00<?, ?it/s]

Loaded: google/gemma-3-4b-it

In [ ]:
judge_results_df = run_vlm_judge(
    df=judge_df,
    out_csv=VLM_OUT,
    model_key=JUDGE_MODEL_KEY,
    prompt_variant=PROMPT_VARIANT,
    save_every=25
)

judge_results_df.head()

[CHK] saved 25 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 50 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 75 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 100 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 125 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 150 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 175 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 200 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 225 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 250 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 275 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 300 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 325 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 350 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 375 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 400 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 425 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 450 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 475 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 500 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 525 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 550 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 575 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 600 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 625 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 650 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 675 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 700 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 725 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 750 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 775 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 800 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 825 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 850 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 875 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 900 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 925 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 950 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 975 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 1000 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 1025 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 1050 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 1075 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 1100 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 1125 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 1150 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 1175 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 1200 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 1225 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 1250 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 1275 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 1300 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 1325 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 1350 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 1375 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 1400 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 1425 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 1450 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 1475 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 1500 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 1525 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 1550 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 1575 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 1600 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 1625 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 1650 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 1675 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 1700 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 1725 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 1750 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 1775 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 1800 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 1825 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 1850 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 1875 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 1900 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 1925 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 1950 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 1975 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 2000 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 2025 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 2050 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 2075 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 2100 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 2125 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 2150 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 2175 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 2200 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 2225 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 2250 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 2275 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 2300 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 2325 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 2350 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 2375 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 2400 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 2425 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 2450 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 2475 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 2500 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 2525 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 2550 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 2575 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 2600 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 2625 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 2650 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 2675 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 2700 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 2725 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 2750 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 2775 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 2800 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 2825 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 2850 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 2875 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 2900 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 2925 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 2950 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 2975 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 3000 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 3025 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 3050 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 3075 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 3100 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 3125 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 3150 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 3175 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 3200 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 3225 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 3250 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 3275 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 3300 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 3325 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 3350 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 3375 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 3400 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 3425 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 3450 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 3475 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 3500 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 3525 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 3550 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 3575 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 3600 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 3625 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 3650 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 3675 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 3700 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv
[CHK] saved 3725 rows -> /content/drive/MyDrive/Vision_Language_Models_Spatial_Understanding/tables/vlm_judge_gemma3_4b_prompt_v2.csv

,prompt_id,split,gen_model,seed,image_path,text,judge_model,prompt_variant,presence_score,relation_score,reason,parse_ok,raw_output,gt_presence_proxy,gt_relation_proxy
0,complex_000000,complex,flux,0,/content/drive/MyDrive/Vision_Language_Models_...,The red hat was on top of the brown coat rack.,gemma3_4b,prompt_v2,5,5,The red hat is clearly present on top of the b...,1,"```json\n{\n ""presence_score"": 5,\n ""relatio...",0.0,NaN
1,complex_000000,complex,flux,1,/content/drive/MyDrive/Vision_Language_Models_...,The red hat was on top of the brown coat rack.,gemma3_4b,prompt_v2,5,5,The red hat is clearly present on top of the b...,1,"```json\n{\n ""presence_score"": 5,\n ""relatio...",0.0,NaN
2,complex_000000,complex,flux,2,/content/drive/MyDrive/Vision_Language_Models_...,The red hat was on top of the brown coat rack.,gemma3_4b,prompt_v2,3,4,"The hat is present, but the coat rack is not. ...",1,"```json\n{\n ""presence_score"": 3,\n ""relatio...",0.0,NaN
3,complex_000001,complex,flux,0,/content/drive/MyDrive/Vision_Language_Models_...,The blue water bottle was on top of the red ba...,gemma3_4b,prompt_v2,5,5,The blue water bottle is clearly on top of the...,1,"```json\n{\n ""presence_score"": 5,\n ""relatio...",0.0,NaN
4,complex_000001,complex,flux,1,/content/drive/MyDrive/Vision_Language_Models_...,The blue water bottle was on top of the red ba...,gemma3_4b,prompt_v2,5,5,The blue water bottle is clearly present on to...,1,"```json\n{\n ""presence_score"": 5,\n ""relatio...",0.0,NaN

In [ ]:
judge_results_df.groupby(["split", "gen_model"])[["presence_score", "relation_score"]].mean()

                      presence_score  relation_score
split      gen_model
3d_spatial flux             4.292222        4.475556
           sdxl             4.375556        4.651111
complex    flux             4.586667        4.907778
           sdxl             4.410000        4.807778
numeracy   flux             4.336667        4.644444
           sdxl             4.144444        4.564444
spatial    flux             4.641111        4.664444
           sdxl             4.712222        4.757778

In [ ]:
# binary conversion for the judge
judge_results_df["presence_bin"] = judge_results_df["presence_score"].apply(
    lambda x: 1 if pd.notna(x) and x >= 4 else (0 if pd.notna(x) and x <= 2 else np.nan)
)
judge_results_df["relation_bin"] = judge_results_df["relation_score"].apply(
    lambda x: 1 if pd.notna(x) and x >= 4 else (0 if pd.notna(x) and x <= 2 else np.nan)
)

# relation proxy bin
def relation_proxy_bin(row):
    split = row["split"]
    gt = row["gt_relation_proxy"]
    if pd.isna(gt):
        return np.nan
    if split == "numeracy":
        # exact-positive only
        return 1 if gt >= 0.999 else 0
    return int(gt >= 0.5)

judge_results_df["gt_relation_bin"] = judge_results_df.apply(relation_proxy_bin, axis=1)

def binary_accuracy(sub, pred_col, gt_col):
    sub = sub[[pred_col, gt_col]].dropna()
    if len(sub) == 0:
        return np.nan
    return (sub[pred_col] == sub[gt_col]).mean()

binary_summary = []
for (split, gen_model), sub in judge_results_df.groupby(["split", "gen_model"]):
    binary_summary.append({
        "split": split,
        "gen_model": gen_model,
        "relation_bin_acc": binary_accuracy(sub, "relation_bin", "gt_relation_bin")
    })

binary_summary_df = pd.DataFrame(binary_summary)
binary_summary_df

        split gen_model  relation_bin_acc
0  3d_spatial      flux          0.338369
1  3d_spatial      sdxl          0.354396
2     complex      flux          0.880000
3     complex      sdxl          0.857143
4    numeracy      flux          0.045300
5    numeracy      sdxl          0.044521
6     spatial      flux          0.621951
7     spatial      sdxl          0.594667

In [ ]:
corr_rows = []
for (split, gen_model), sub in judge_results_df.groupby(["split", "gen_model"]):
    sub = sub[["relation_score", "gt_relation_proxy"]].dropna()
    if len(sub) >= 3:
        rho, p = spearmanr(sub["relation_score"], sub["gt_relation_proxy"])
    else:
        rho, p = np.nan, np.nan
    corr_rows.append({
        "split": split,
        "gen_model": gen_model,
        "spearman_relation_vs_proxy": rho,
        "p_value": p,
        "n": len(sub)
    })

corr_df = pd.DataFrame(corr_rows)
corr_df

        split gen_model  spearman_relation_vs_proxy       p_value    n
0  3d_spatial      flux                   -0.464080  2.697169e-19  335
1  3d_spatial      sdxl                   -0.242399  2.625750e-06  367
2     complex      flux                    0.344828  9.139226e-02   25
3     complex      sdxl                    0.222222  3.329584e-01   21
4    numeracy      flux                    0.153911  3.508298e-06  900
5    numeracy      sdxl                    0.096057  3.921923e-03  900
6     spatial      flux                    0.102676  6.245433e-02  330
7     spatial      sdxl                   -0.057232  2.676604e-01  377

## 20. Summary of This Notebook

In this notebook, we implemented the **VLM-as-a-Judge evaluation stage** of the project.

## What was done in this notebook
Using the generated images from Notebook 1 and the benchmark prompts, this notebook evaluated image-prompt alignment with multiple **Vision-Language Model judges**. The judges were asked to assess each generated image based only on:
- the **generated image**, and
- the **original prompt used for generation**.

This was done intentionally so that the VLM judges remain **independent** from the automatic extraction pipeline developed in Notebook 2.

## Judge models evaluated
This notebook runs the evaluation with multiple VLM judges, including:
- **Qwen2.5-VL**
- **Qwen3-VL**
- **Gemma 3** (when model access is available)

These models were chosen to compare different multimodal LLM families and to test whether some VLMs are more reliable than others as judges of compositional image generation.

## Prompt variants evaluated
The notebook also evaluates multiple **judge prompt variants**.

All prompt variants follow the same core idea:
- score whether the required objects are present in the image,
- score whether the intended relation, count, or overall composition is correct,
- and return the result in a structured JSON format.

The difference between prompt variants is the **instruction style**:
- one variant uses a **shorter and simpler instruction**,
- another uses a **more explicit rubric**, where the meaning of each score from **1 to 5** is defined more clearly.

This allows us to test whether the behavior of the VLM judges depends not only on the model itself, but also on how the judging task is phrased.

## Outputs produced
For each image and each judge configuration, this notebook stores:
- the prompt ID,
- the dataset split,
- the generator model,
- the random seed,
- the judge model,
- the prompt variant,
- the VLM `presence_score`,
- the VLM `relation_score`,
- the judge explanation,
- the raw model output,
- and the proxy reference values from Notebook 2.

These results are saved in CSV files so that different judge runs remain directly comparable.

## Role of this notebook in the full project
This notebook does **not** perform the final interpretation of the results.  
Instead, its role is to generate the structured judge outputs needed for the final stage of the project.

The detailed **explanation, comparison, and analysis of results** will be presented in the **final notebook**, where we will:
- merge the outputs from all previous notebooks,
- compare VLM judge scores with the automatic proxy labels from Notebook 2,
- evaluate agreement and correlation across splits,
- compare judge models and prompt variants,
- compare SDXL and FLUX,
- and analyze disagreement cases qualitatively.

## Conclusion
In summary, this notebook produced the complete **VLM-as-a-Judge evaluation outputs** required for the project.  
These outputs will serve as the main input for the final notebook, where the full experimental analysis and interpretation will be carried out.